### ISSUE TITLE
Native callback doesn't invoke action in c#

### ISSUE THREAD

**Issue by nilsk123** [lupidan/apple-signin-unity#101]
**iOS 14.4 on an iPhone SE**
**Unity 2020.2.5f1**
**latest plugin version**

Hello, I've been trying to setup Apple sign in using this plugin but I'm stuck.

I can succesfully call LoginWithAppleId, the prompt comes up and allows me to then login, but the success and error callbacks are never fired on the C# side of things (thus I don't receive the credentials)

Here's what i have observed:

 - The AppleAuthManager adds a callback and receives a requestId of 1 (which makes sense)
 - The native side (AppleAuthManager.m) receives this requestId correctly and performs the authorization request
 - Authorisation succeeds after entering pin (didCompleteWithAuthorization is fired)
 - sendNativeMessageForDictionary is called using the correct requestId
 - sendNativeMessageForString is called using the correct requestId
 
This is where it ends. The apple prompt disappears and the unity side of things becomes active again, but no callback is fired. I just had a quick look at the messaging setup but don't fully understand it. I don't think the Update function in the authmanager is ever called, so pending callbacks aren't executed. Where is this supposed to be called from, if its not a monobehaviour?

I have added logging statements like so:

```
public void PerformLoginWithAppleIdAndFirebase(Action<FirebaseUser> firebaseAuthCallback)
    {
        var rawNonce = GenerateRandomString(32);
        var nonce = GenerateSHA256NonceFromRawNonce(rawNonce);

        var loginArgs = new AppleAuthLoginArgs(
            LoginOptions.None,
            nonce);

        this.appleAuthManager.LoginWithAppleId(
            loginArgs,
            credential =>
            {
                UnityEngine.Debug.Log("Credentials received");
                var appleIdCredential = credential as IAppleIDCredential;
                if (appleIdCredential != null)
                {
                    this.PerformFirebaseAuthentication(appleIdCredential, rawNonce, firebaseAuthCallback);
                }
            },
            error =>
            {
                // Something went wrong
                UnityEngine.Debug.LogError("Credentials not received")
            });
    }

```

**Comment by lupidan** [comment]
Are you regularly calling Update on the Auth manager?


[https://github.com/lupidan/apple-signin-unity#initializing](https://github.com/lupidan/apple-signin-unity#initializing)

[https://github.com/lupidan/apple-signin-unity#why-do-i-need-to-call-update-manually-on-the-appleAuthManager-instance](https://github.com/lupidan/apple-signin-unity#why-do-i-need-to-call-update-manually-on-the-appleAuthManager-instance)

**Comment by nilsk123** [comment]
I have no idea how I missed this, thanks for the resopnse

Will check this later!
