### ISSUE TITLE
Symbols not being found

### ISSUE THREAD

**Issue by lebasp** [lupidan/apple-signin-unity#103]
Using github package manager version 

Unity 2019.4
Xcode 12.2
AuthenticationServices.framework (from iOS SDK 14.2)
Target iOS 13.0

![image](https://user-images.githubusercontent.com/4662018/113591856-d1491880-960a-11eb-8cad-37408f4cda99.png)

**Comment by lebasp** [comment]
Fixed by not using the package manager version, and changing the settings on "AppleAuthManager" files with AuthenticationService on Unity 2019.4

![image](https://user-images.githubusercontent.com/4662018/113600637-ae246600-9616-11eb-8a54-7724f660e9e3.png)

**Comment by lupidan** [comment]
If you do that, your games will crash on iOS 13.

You are supposed to setup the framework and entitlement in a post-processor script. It's all documented.
https://github.com/lupidan/apple-signin-unity#programmatic-setup-with-a-script

**Comment by lebasp** [comment]
Oh I see, the main problem is thisAddSignInWithAppleWithCompatibility only works in unity 2020 :(

on Unity 2019, the AddSignIn doesn't accept UnityFramework target as a parameter
https://docs.unity3d.com/2019.4/Documentation/ScriptReference/iOS.Xcode.ProjectCapabilityManager.html

**Comment by lebasp** [comment]
Probly need something like that

`     var manager = new ProjectCapabilityManager(projectPath, "Entitlements.entitlements", null, project.GetUnityMainTargetGuid());
            manager.AddSignInWithApple();
            manager.WriteToFile();
            
            manager = new ProjectCapabilityManager(projectPath, "Entitlements.entitlements", null, project.GetUnityFrameworkTargetGuid());
            manager.AddSignInWithApple();
            manager.WriteToFile();`

**Comment by lupidan** [comment]
`AddSignInWithAppleWithCompatibility` is a different method from `AddSignInWithApple`

`AddSignInWithApple` is offered by the Unity SDK, it does not work properly if the app is divided in two different targets (like in 2020), and I believe adds the framework as mandatory, which crashes on iOS 12 and previous

`AddSignInWithAppleWithCompatibility` is an extension method provided by this plugin that solves the issue. It's a completely different method from the previously mentioned.

Read the documentation please.
https://github.com/lupidan/apple-signin-unity#programmatic-setup-with-a-script
