### ISSUE TITLE
Plugin works the first time, but doesn't after revoking credentials

### ISSUE THREAD

**Issue by NCura** [lupidan/apple-signin-unity#104]
Hello, I'm using your plugin with Firebase Auth, and it worked perfectly. I was able to add it to my project and create a new user in Firebase using Apple and play my game.
I then logged out manually from Firebase (using FirebaseAuth.SignOut()) and then I revoked the credentials through settings to re test again (the way it's mentionned in the FAQ, going to Settings, iTunes user...). 
Going back to the app and trying to Sign In with Apple again, I'm getting Apple's popup asking if I want to share my email or not and then, after pressing "Continue with Password", the popup just dissapears and nothing happens (unlike the first time, where I was able to create an account). When trying to Sign In once again, I get the short popup from Apple asking to sign in again). When checking in my iTunes settings, my app is appearing once again, meaning that it was correctly registered. 

I add some Debug.Log in Unity : 
- One before calling _appleAuthManager.LoginWithAppleID
- One inside the successCallback
- One inside the errorCallback

After building and running it in my iPhone through Xcode, the first log is displayed (meaning LoginWithAppledID is called), but then, I don't receive any more logs (besides applicationWillResignActive() and applicationDidBecomeActive() before and after the Apple's popup).

Do I need to do something more after revoking the credentials, in order to re-test account creation ?

Thank you very much for your help.

**Comment by lupidan** [comment]
Are you by any chance creating a new instance of the `AppleAuthManager` every login/sign in attempt, and calling `Update` only on the first one (the one that works)?

From what you are writing, it seems that the success/fail callbacks are not being triggered in Unity, which is something that might happen when `Update` is not called on the `AppleAuthManager`.

If you have any sample project that reproduces the issue I could take a look.

**Comment by NCura** [comment]
No, the initialization is only done once and the update is called on that one instance.
But you were right, I found the problem. I have a plain c# class that I use as `AppleSignInManager` and then I hook up the `AppleAuthManager` to another MonoBehaviour class in order to call it's update method. It turns out that the `AppleAuthManager` in the MonoBehaviour was not being assign and the `AppleAuthManager.Update()` wasn't being called.

Thank you for your help and for this great plugin !

TL.DR. For everyone having this problem, always check that you are calling the `Update` method on the `AppleAuthManager`

**Comment by lupidan** [comment]
Glad to hear!!
And thanks for the advice for everyone 😄
