### ISSUE TITLE
Getting "AppleAuth.Native.AppleError" error 

### ISSUE THREAD

**Issue by surajsk1812** [lupidan/apple-signin-unity#105]
Hello,
I am using your plugin. 
I am using unity 2019.4.14f version.
I have created a AppleSignInManager.cs script to signin with apple.
Getting "AppleAuth.Native.AppleError" error in logs when I click on apple signin button.

[AppleSignInManager.pdf](https://github.com/lup
![SigninApple](https://user-images.githubusercontent.com/56722820/115715637-f7561300-a395-11eb-840e-dab34500535b.png)
idan/apple-signin-unity/files/6358241/AppleSignInManager.pdf)

Thank You

**Comment by surajsk1812** [comment]
[AppleSignInManager.pdf](https://github.com/lupidan/apple-signin-unity/files/6358251/AppleSignInManager.pdf)

**Comment by lupidan** [comment]
The plugin is just a wrapper around the Apple Sign In feature in the iOS SDK. It returns the same Apple Error you get while attempting to sign in.

From experience, when you are getting an Unknown error (what I can see in the screenshot), it's caused pretty much when having a wrong capabilities setup, code signing setup and/or a wrong setup for the app in your apple developer's account.

Make sure you are setting the post-processing correctly to add entitlements:
https://github.com/lupidan/apple-signin-unity#plugin-setup-iostvos

There is also some official documentation on how to set it up.
https://help.apple.com/developer-account/?lang=en#/devde676e696

Finally, I would recommend to run the app from Xcode, and look for any error messages from Apple in the Xcode log, that might give you more information.

**Comment by surajsk1812** [comment]
Not getting apple user name at first time too.

**Comment by surajsk1812** [comment]
Even app was there in settings to revoke
