### ISSUE TITLE
Please add assembly definition

### ISSUE THREAD

**Issue by derwaldgeist** [lupidan/apple-signin-unity#109]
We're preparing our Unity project for Unit Testing and are facing the issue that this requires us to setup assembly definitions for our code. Which in turn requires us to add .asmdefs to all third party libraries as well, so we can reference them.

Since we're using the Unity Repository version of `apple-signin-unity`, we can't add the .asmdef file manually. AFAIK, this is only possible if you keep the library in your Assets folder.

Thus it would be awesome if you could provide one as part of the distribution. Thanks.

**Comment by lupidan** [comment]
I'm not sure I understand your request. The current version of the repository **contains** assembly definitions:

https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/AppleAuth.asmdef
https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/Editor/AppleAuth.Editor.asmdef

**Comment by derwaldgeist** [comment]
Ooops, seems as if I just didn't see them. Sorry for bothering, and thanks for the super-fast response!
