### ISSUE TITLE
FullName is always empty

### ISSUE THREAD

**Issue by HaakonL** [lupidan/apple-signin-unity#11]
Hi, everything with this plugin works really well, except the FullName property is empty both in QuickLogin and Login.

LoginOptions.IncludeFullName is set, of course.

Any suggestions?

Also missing a Logout()... :)

**Comment by daniel-ys** [comment]
Remember this is supposed to be a wrapper around Apple's Sign In with Apple feature.
This seems to be a similar case as the issue present here: #9 

It looks like the full name and/or email is only given the FIRST time the user tries to Login, when there are no credentials generated for your app.
Even if you try to perform a Login afterwards with email and name request, it's considered same or similar to a quick login, so only the Apple ID is returned.
Your app should be responsible of saving that user information somewhere, to safely send it to your server, where the user is created.

As this is a wrapper around Apple's functionality, there is no Logout option. How Apple expects you to "Logout" is by accessing `Settings` => `Click your iTunes user` => `Password & Security` => `Apple ID logins`. There you can select the app and click on Stop using Apple ID
After this, the credentials are effectively revoked, your app will receive a [Credentials Revoked notification](https://github.com/lupidan/apple-signin-unity#listening-to-credentials-revoked-notification), and next time you try to Login, you should receive name and/or email.

I need to add this information in the documentation of this plugin though... Let me know if this answers your question. 👍

**Comment by lupidan** [comment]
Remember this is supposed to be a wrapper around Apple's Sign In with Apple feature.
This seems to be a similar case as the issue present here: #9 

It looks like the full name and/or email is only given the FIRST time the user tries to Login, when there are no credentials generated for your app.
Even if you try to perform a Login afterwards with email and name request, it's considered same or similar to a quick login, so only the Apple ID is returned.
Your app should be responsible of saving that user information somewhere, to safely send it to your server, where the user is created.

As this is a wrapper around Apple's functionality, there is no Logout option. How Apple expects you to "Logout" is by accessing `Settings` => `Click your iTunes user` => `Password & Security` => `Apple ID logins`. There you can select the app and click on Stop using Apple ID
After this, the credentials are effectively revoked, your app will receive a [Credentials Revoked notification](https://github.com/lupidan/apple-signin-unity#listening-to-credentials-revoked-notification), and next time you try to Login, you should receive name and/or email.

I need to add this information in the documentation of this plugin though... Let me know if this answers your question. 👍

**Comment by HaakonL** [comment]
Hi,

thanks for the quick feedback. It's clear, and noted 👍 :).
