### ISSUE TITLE
VPN issues

### ISSUE THREAD

**Issue by dalkia** [lupidan/apple-signin-unity#113]
Hello!

So, I've implemented the plugin, tested it and confirmed it worked correctly. Nonetheless, when submitted to the app store, I was rejected with the following image:

<img width="1112" alt="Reject" src="https://user-images.githubusercontent.com/1999557/126189004-43fb78f4-b56b-4a4e-9bf4-0f544578e330.png">

After making some research and testing, I found out the the plugin doesnt work if the device is in a VPN. Aparently, the plugin cannot comunicate with the Apple server when inside the VPN.

Has anyone dealed with this issue? I m thinking if there is a workaround, or what should I answer to Apple before resubmitting.

Thanks!

**Comment by lupidan** [comment]
> Aparently, the plugin cannot comunicate with the Apple server when inside the VPN.

The plugin is a wrapper around a native iOS functionality provided **directly by Apple**. It does not implement any custom connections to anything.

From what I can see in the image, the plugin is correctly creating the request for Name and E-mail, and presenting the native popup to communicate with Apple. _Whatever happens within that native popup, is Apple's responsibility._

The plugin just receives a Success/Failed callback whenever Apple decides to close the popup and send either one. It seems they are not sending one when it fails to connect, possibly to allow for a retry.

Is this really an Apple rejection? Did you carefully read the message regarding the rejection? If the case still applies, I am sorry to say you have just encountered an Apple reviewer that was having a bad day, or doesn't really understand a functionality of their SDK. I wouldn't be surprised.

I would suggest an rejection appeal.

**Comment by dalkia** [comment]
Hello! 

Okay, send the appeal. I ll let you know the result. Apparently this is something that happens with VPN and Apple Sign In. 
(https://discussions.apple.com/thread/250761596)

Thanks for the help!

**Comment by dalkia** [comment]
Yeap, appealing worked. My app has been approved in the Apple Store. Just in case anyone gets rejected due to the same reason, just appeal!

Thanks for your help @lupidan
