### ISSUE TITLE
Popup prompted twice

### ISSUE THREAD

**Issue by albert-pixel** [lupidan/apple-signin-unity#114]
Hi!

We are testing the plugin on Sandbox environment. Everything works fine, but the window/pop up that ask for the sign in confirmation appears twice. You know, the one that says to the user "Do you want to sign in to APPNAME" with your Apple ID xxx"?
Once the users confirms that he wants to continue, then a passcode/face id or whatever, is asked. After confirming, the window disappears and a couple of seconds later, it appear agains, saying the same and asking the same.
After confirming this second windows, everything goes well.

We know from the logs that the devices receives the data after the first window confirmation, so we don't understand why the second window appears...
It's an error? It's a sandbox issue?

Thanks!

**Comment by lupidan** [comment]
Sounds to me you are calling the Login method twice...

If you are debugging on Xcode, I would suggest to put breakpoints in AppleAuthManager.m:

 [Here](https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Native/iOS/AppleAuthManager.m#L373) and [here](https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Native/iOS/AppleAuthManager.m#L380)


... to debug if that's the case

**Comment by albert-pixel** [comment]
Thanks for your quickly response!
I added the breakpoints, and the method "AppleAuth_LoginWithAppleId" it's called twice. So I my fault, I will check the code.

Sorry for bothering you :(

**Comment by RomainBitard** [comment]
I've got it twice too but I don't call the login with apple id twice in the same code path, I think there is something funny in how success and error callback are called  that I don't understand probably
