### ISSUE TITLE
Did metal Api Needed To Run Apple Signin?

### ISSUE THREAD

**Issue by CLOUDFIRE91** [lupidan/apple-signin-unity#115]
Hi All 

I have tried this code. Wheni run in ipad. It asks the app cant install because your app did not support metal. 

Actually My ipad  wont support Metal  and also i think  it supports only ios14... But my ios 10.1 only.. 

is there any way i can integrate sign in apple ...  What i have to do???

**Comment by lupidan** [comment]
This issue is _completely unrelated_ to this plugin...

Metal is a graphics layer, and you are building your app with it.
Your device does not support the Metal graphics layer.
