### ISSUE TITLE
Not working on iPad (v15.0), "Canceled error"

### ISSUE THREAD

**Issue by josValentin** [lupidan/apple-signin-unity#119]
On ipad devices is getting the error "Canceled" like it was canceled by the user but it's not the case, on iphone device seems to work ok, hope you can help me :c

**Comment by lupidan** [comment]
I don´t have an iPad at hand to test this.
The most I can do is check on the simulator this weekend.

Are you sure the iPad has an iTunes user logged in? What does the Xcode log say?

**Comment by lupidan** [comment]
The login dialog seems to appear nicely on the simulator... 🤷‍♀️
<img width="716" alt="Meh" src="https://user-images.githubusercontent.com/1314521/134739532-4739dad1-a782-477c-bd7a-da1acd903320.png">

If you have a video and a full Xcode log of the session, that would be a good starting point...

**Comment by lupidan** [comment]
Closing due to inactivty.
If anyone experiences this, and has some Xcode logs or some video proof, feel free to reopen.

**Comment by lupidan** [comment]
Hi @hnguyen094 

First of all, **thanks** for the detailed log.
I see in it some `SignInWithAppleExistingAccount` class from your codebase is involved

* Is this cancelled happening when attempting a [QuickLogin call](https://github.com/lupidan/apple-signin-unity#quick-login)?
* Or does it happen when attempting a full [LoginWithAppleId call](https://github.com/lupidan/apple-signin-unity#perform-sign-in-with-apple)?
* Does the screen fade to black at all?
* Does the sign in native window show up at all?

The only thing I can test against is an iPad simulator, I do not have an iPad device with iOS 15.

**Comment by lupidan** [comment]
@hnguyen094 @josValentin Ok, I figured the issue out.

This seems to be happening whenever calling Quick Login on iPad, and the current Apple user having signed in with Apple before with you application. It should display the quick login popup, but it's failing with cancelled error.

For some reason I don't comprehend, Apple is now not accepting a `ASAuthorizationPasswordRequest` to check if there are any stored passwords in the keychain... Even though that's [how they are doing it](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple?language=objc) in their official Sign In With Apple example...


**For the quickest fix**, you can replace the line here:

https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Native/iOS/AppleAuthManager.m#L101

With this:

```
ASAuthorizationController *authorizationController = [[ASAuthorizationController alloc] initWithAuthorizationRequests:@[appleIDRequest]];
```

That should trigger the quick login.

<img width="716" alt="Screenshot 2021-10-06 at 22 40 06" src="https://user-images.githubusercontent.com/1314521/136271970-d4679f89-a77e-4b97-a1e8-58bf7f79cc9a.png">

**Comment by lupidan** [comment]
I'll try to work on a fix for this during the weekend. Maybe the keychain check should be something optional to configure.

With that said, this is most definitely an **iOS 15.0 bug**. Specially considering it works on iOS, and also considering that this keychain check is something they recommend doing for checking existing users in their [official example](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple?language=objc). ⬇️ 

<img width="629" alt="Screenshot 2021-10-06 at 22 43 17" src="https://user-images.githubusercontent.com/1314521/136272310-b1302661-b684-43d8-a894-37aaca4efd4e.png">

**Comment by hnguyen094** [comment]
@lupidan I think I also found something but it's slightly different:

For iPadOS 14.x, `QuickLogin` calls `successCallback(null)` when it fails (user has not signed in before.)
For iPadOS 15.x, `QuickLogin` calls `errorCallback` when it fails, with an `error.AuthorizationErrorCode == AuthorizationErrorCode.Canceled`.

My current code:
`successCallback(credential)` => Sign in with token/auth
`successCallback(null)` => Do `LoginWithAppleId`
`errorCallback(err)` => bubble error & complain to user

What I can change it to for it to work:
`successCallback(credential)` => Sign in with token/auth
`successCallback(null)` OR `errorCallback(err)` => Do `LoginWithAppleId`

**Comment by lupidan** [comment]
`ASAuthorizationPasswordRequest` tries to retrieve an [existing iTunes keychain credential pair](https://github.com/lupidan/apple-signin-unity#ios-keychain-support) (user&password) saved in the user's keychain, for your app. 
This was used before Apple ID was ever introduced, so they introduced it to help support existing users of the keychain.

With that said, if you never stored any credentials for your app in the user's iTunes keychain, it's safe to apply my proposed change.

**Comment by lupidan** [comment]
@hnguyen094 
Sorry for spamming, but while testing on the iPad simulator again, it seems that Apple is not returning Cancelled anymore, could it be that they have fixed the problem on real devices? Let me know if this is the case.

I don´t have a real iPad for testing.

**Comment by hnguyen094** [comment]
I don't have my dev env setup, but my app behavior suggests that it might have been fixed. There was no iPadOS update though, so if there was any change it was server-side.
