### ISSUE TITLE
AKAuthenticationError Code=-7026

### ISSUE THREAD

**Issue by Scott-iSweety** [lupidan/apple-signin-unity#12]
My Apple Sign In is working fine when I run my app by Xcode in development mode.

After I archive a distribution IPA, my co-worker will replace provisioning profile and bundle ID for publishing to TestFlight, and then Apple Sign In can't work anymore but show this error when I try to sign in with Apple.

`Authorization failed: Error Domain=AKAuthenticationError Code=-7026 UserInfo={AKClientBundleID=<private>}`

I search some articles on Google, all they say is that I probably forgot to add capability, but I actually add the "Sign In with Apple" capability and run it by Xcode successfully.

Is there any possibility that my co-worker's provisioning profile missing settings?(We are cross-country partner so I can't easily check their settings)

Or something should be modified before I archive a distribution IPA?

**Comment by Scott-iSweety** [comment]
Found Problem, my partner's Entitlement didn't set correctly

```
        <key>com.apple.developer.applesignin</key>
        <array>
                <string>Default</string>
        </array>
```

this should be add to Entitlements correctly.

**Comment by lupidan** [comment]
Sorry I couldn't answer sooner. I was going to suggest something was definitely wrong when replacing the provisioning profile if it worked fine before doing so.

Glad to hear the issue was solved. 👍 
Thanks for closing the issue!
