### ISSUE TITLE
IOS build failed wih Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by JoyalRedDevil** [lupidan/apple-signin-unity#120]
Undefined symbols for architecture arm64:
  "_UnitySignInWithApple_Login", referenced from:
      _SignInWithApple_LoginInternal_mF47ED0923886387AC79573DD52A2A75D6D8F1FFD in Assembly-CSharp38.o
      _SignInWithApple_UnitySignInWithApple_Login_m5A2EF436C683C71D2D6E034D838FD05FDA6F6D3C in Assembly-CSharp38.o
     (maybe you meant: _SignInWithApple_UnitySignInWithApple_Login_m5A2EF436C683C71D2D6E034D838FD05FDA6F6D3C)
  "_UnitySignInWithApple_GetCredentialState", referenced from:
      _SignInWithApple_GetCredentialStateInternal_mE7725CD83B2C11D10EC76EB24DC795ADBE20DB27 in Assembly-CSharp38.o
      _SignInWithApple_UnitySignInWithApple_GetCredentialState_m2DC81A39E66199A01BC2B1B0CBD3C0EB811137D8 in Assembly-CSharp38.o
     (maybe you meant: _SignInWithApple_UnitySignInWithApple_GetCredentialState_m2DC81A39E66199A01BC2B1B0CBD3C0EB811137D8)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="1080" alt="MicrosoftTeams-image (7)" src="https://user-images.githubusercontent.com/66636631/135964676-5a0f9df5-25d1-4f02-91e4-67626532b06b.png">

**Comment by lupidan** [comment]
What?

Those symbols are from Unity's official Sign in With Apple package. **This repository is for a completely different plugin**.
Please refer your request to Unity support.

**Comment by eatsports** [comment]
Hello, i have a similar issue, but this time it points to AppleAuthManager class:

 Undefined symbols for architecture arm64:
     "_OBJC_CLASS_$_ASPasswordCredential", referenced from:
         objc-class-ref in AppleAuthManager.o
     "_OBJC_CLASS_$_ASAuthorizationAppleIDCredential", referenced from:
         objc-class-ref in AppleAuthManager.o
     "_OBJC_CLASS_$_ASAuthorizationController", referenced from:
         objc-class-ref in AppleAuthManager.o
     "_OBJC_CLASS_$_ASAuthorizationPasswordProvider", referenced from:
         objc-class-ref in AppleAuthManager.o
     "_ASAuthorizationAppleIDProviderCredentialRevokedNotification", referenced from:
         -[AppleAuthManager registerCredentialsRevokedCallbackForRequestId:] in AppleAuthManager.o
     "_ASAuthorizationScopeFullName", referenced from:
         -[AppleAuthManager loginWithAppleId:withOptions:nonce:andState:] in AppleAuthManager.o
     "_OBJC_CLASS_$_ASAuthorizationAppleIDProvider", referenced from:
         objc-class-ref in AppleAuthManager.o
     "_ASAuthorizationScopeEmail", referenced from:
         -[AppleAuthManager loginWithAppleId:withOptions:nonce:andState:] in AppleAuthManager.o
   ld: symbol(s) not found for architecture arm64

**Comment by lupidan** [comment]
You are not doing the [Postprocessing](https://github.com/lupidan/apple-signin-unity#programmatic-setup-with-a-script) correctly to include the `AuthenticationServices.framework`  in your project.

**Please**, read the documentation

**Comment by eatsports** [comment]
That helped, thanks!
