### ISSUE TITLE
LoginWithAppleId is not called

### ISSUE THREAD

**Issue by equizo** [lupidan/apple-signin-unity#121]
This is a handler of the login button. I see native Apple auth form, but nothing comes in logs: no "login response received" string received and further code is not running.

```
public static void SignIn()
    {
      string rawNonce = AppleAuthUtils.GenerateRandomString(32);
      string nonce = AppleAuthUtils.GenerateSHA256NonceFromRawNonce(rawNonce);
      var loginArgs = new AppleAuthLoginArgs(LoginOptions.IncludeEmail | LoginOptions.IncludeFullName, nonce);

      AppleAuthInstance.AppleAuthManagerImpl.LoginWithAppleId(loginArgs,
        credential => {
          Debug.Log("login response received");
          if (credential is IAppleIDCredential appleIdCredential) {
            Debug.Log("Credentials are ok");
            PerformFirebaseAuthentication(appleIdCredential, rawNonce);
          }
          else {
            Debug.LogError("Credentials are null");
          }
        },
        error => {
          Debug.LogError($"Apple sign in failed:{error.LocalizedFailureReason}\n{error.LocalizedRecoverySuggestion}");
        });
    }
```

**Comment by renanwolf** [comment]
Are you manually invoking `IAppleAuthManager.Update()` on every Unity's update somewhere? See [why do you need to call update manually](https://github.com/lupidan/apple-signin-unity#why-do-i-need-to-call-update-manually-on-the-appleauthmanager-instance)

**Comment by lupidan** [comment]
As @renanwolf mentioned, make sure you are calling `Update` regularly on your created AppleAuthManager.
There is [documentation](https://github.com/lupidan/apple-signin-unity#initializing) on how to setup and initialize the manager, please read it.
