### ISSUE TITLE
QuickLogin error

### ISSUE THREAD

**Issue by LikeGame** [lupidan/apple-signin-unity#131]
Hi, everyone， i need your help when i use quick login.
code:

    private void AttemptQuickLogin()
    {
        var quickLoginArgs = new AppleAuthQuickLoginArgs();
        Debug.Log("AttemptQuickLogin   AttemptQuickLogin");
        this._appleAuthManager.QuickLogin(
            quickLoginArgs,
            credential =>
            {
                Debug.Log("QuickLogin   AttemptQuickLogin");
                var appleIdCredential = credential as IAppleIDCredential;
                if (appleIdCredential != null)
                {
                    Debug.Log("player AttemptQuickLogin ok, player id = " + credential.User);
                    SaveUserId(credential.User);
                }
            },
            error =>
            {
                // If Quick Login fails, we should show the normal sign in with apple menu, to allow for a normal Sign In with apple
                var authorizationErrorCode = error.GetAuthorizationErrorCode();
                Debug.LogError("Quick Login Failed " + authorizationErrorCode.ToString() + " " + error.ToString());

                Debug.LogError("AttemptQuickLogin error, login with password");
                SignInWithApple();
            });
    }

error msg:
[core] Authorization failed: Error Domain=AKAuthenticationError Code=-7089 "(null)"

**Comment by LikeGame** [comment]
I googled it but couldn't find it. What do I do。thank you！

**Comment by lupidan** [comment]
From the documentation:

![Screenshot 2021-11-09 at 23 01 41](https://user-images.githubusercontent.com/1314521/141004109-3d6cf42c-ac07-472e-b04c-32be85239060.png)

Also, in the code you copy pasted from the [official example](https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuthSampleProject/Assets/AppleAuthSample/MainMenu.cs#L182):
```
// If Quick Login fails, we should show the normal sign in with apple menu, to allow for a normal Sign In with apple
```

Closing...
