### ISSUE TITLE
Get email and IdToken

### ISSUE THREAD

**Issue by kadirmenz** [lupidan/apple-signin-unity#139]
Hi I use this package in my project,
I need to get email and IdToken from identityToken.
I tried appleIdCredential.email but may be its wrong because I canr send datas to my own backend.
I need to send IdToken and Email which comes from apple sign in. Do you know any solutşon to get them?

**Comment by lupidan** [comment]
There is an extensive [documentation](https://github.com/lupidan/apple-signin-unity#readme) available, please read it.
The `IdentityToken` comes in the received credentials.
https://github.com/lupidan/apple-signin-unity#perform-sign-in-with-apple
