### ISSUE TITLE
Unable to decode header as Base64Url encoded string

### ISSUE THREAD

**Issue by goodspeed3** [lupidan/apple-signin-unity#141]
Hello,
Thanks for this library.

When running this in my project, I get the following error message -- any ideas how to fix? The header and sig don't look to be base64url encoded.

`IDX12729: Unable to decode the header '000632' as Base64Url encoded string. jwtEncodedString: '000632.1ce5b7.....13335.0609'.`

I setup according to the sample source code:
`        if (AppleAuthManager.IsCurrentPlatformSupported)
        {
            // Creates a default JSON deserializer, to transform JSON Native responses to C# instances
            var deserializer = new PayloadDeserializer();
            // Creates an Apple Authentication manager with the deserializer
            this._appleAuthManager = new AppleAuthManager(deserializer);    
        }
`

**Comment by lupidan** [comment]
From a quick google search, that error code seems to come from some JWT parsing library you are using, which is not something this plugin provides.
It also looks to me that you might be using the wrong field to decode it as a JWT. The JWT token is the `IdentityToken` [here](https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Interfaces/IAppleIDCredential.cs#L10), not the `User`

**Comment by goodspeed3** [comment]
Ah, thanks.  That was the fix.
