### ISSUE TITLE
What dfference between QuickLogin and LoginWithAppleId?

### ISSUE THREAD

**Issue by orangeagain** [lupidan/apple-signin-unity#144]
The only difference I found so far is that one with Email and one without, So what are the benefits of quick login?

**Comment by orangeagain** [comment]
I haven't studied it carefully, but the official example doesn't seem to distinguish between LoginWithAppleId() and QuickLogin()？
![image](https://images.xiaozhuanlan.com/photo/2019/89a8e2a1011edd569af968c9584d889f.jpg)

**Comment by lupidan** [comment]
"QuickLogin" should be renamed eventually to "CheckExistingCredentials"
It´s useful after an app re-install:
- To check if the user already used SIWA in the past, if so, the SIWA prompt appears for re-authorization
- To check if an already existing iCloud Keychain Credential exist for the app, if so, it returns an IPasswordCredential

If none of those exist, "QuickLogin" fails, whereas "LoginWithAppleId" prompts the user to authorize SIWA

Closing
