### ISSUE TITLE
AuthorizationError Code=1001

### ISSUE THREAD

**Issue by wagenheimer** [lupidan/apple-signin-unity#145]
Hi! Thanks for the plugin!
I'm trying to make it work with my game, but It fails on the AttempQuickLogin method.

[Authorization] ASAuthorizationController credential request failed with error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1001 "(null)"

I saw some reports of the same problem where it says that error 1001 is because it was canceled. But no pop up is shown and the error happens before the pop up is shown.

Is there anything I can check?

I'm testing on a real device, an iPad.

**Comment by lupidan** [comment]
So it´s technically a cancelled error.
- Have you tried the same code on an iPhone?
- Double check you are setting up SIWA correctly with the right entitlements etc...
- Is the account logged in a Testing Sandbox account?
- Does the logged in account have 2FA enabled as it should?
- Consider also the possibility of a temporary Apple server issue for development environments, it wouldn't be the first time...

With that said, the plugin is doing what it should do, return to Unity whatever Apple returns after attempting a SIWA call. So this is not an actual issue of this plugin, but more on your SIWA setup/Apple environment. I would check the official Apple forums for further assistance.

Closing

**Comment by yuchenz27** [comment]
I got the same problem, I am pretty sure I got the entitlement stuff correct
