### ISSUE TITLE
iOS 15.5+ cancels the sign-in process

### ISSUE THREAD

**Issue by Wnntyl** [lupidan/apple-signin-unity#153]
Hi,

We encountered an issue on the latest versions of iOS. 
Any QuickLogin attempt is immediately canceled. The login popup never appears.
Has anyone else encountered such a problem? Any idea how to fix it?

Details:

The problem manifests itself when two things are combined:
- the latest version of iOS (15.5+)
- xcode 13+

If one of the conditions is not met, then the problem does not appear.

For example:
iOS 15.6 and xcode 12.2 work fine together in this regard
iOS 14.4.2 and xcode 13.2 - no problem

but 15.6 and xcode 13.2 - the login doesn't work

Some logs:
```
16:40:36.9535|[LoginScreenMediator] Apple login clicked
16:40:36.9643|[AppleSignIn] Attempting Quick Login
16:40:37.1528|[AppleSignIn] Quick Login: error callback invoked
16:40:37.1533|[AppleSignIn] Quick Login canceled
```

**Comment by ilmarioranen** [comment]
Seems like a serious issue. Does anyone know a solution when using Xcode 13 or 14?

**Comment by Wnntyl** [comment]
I use a workaround.

The problem occurs with the QuickLogin. The iOS/plugin immediately returns a "Cancel" result. To distinguish legitimate user cancellation from this bug, I check how much time elapsed between the login request and the cancellation. If it's less than half a second, I consider it an error and call the full Login.

Alternatively, you can try not to use the QuickLogin at all, but always call the full Login.

**Comment by ilmarioranen** [comment]
Interesting, thanks! Might use that as well. A bit worried about this plugins maintenance though if "this is the way" :)

**Comment by lupidan** [comment]
"QuickLogin" should be renamed to "CheckExistingCredentials"...

Basically, "QuickLogin" is supposed to just fail if no previous SIWA credentials were created, and no username+password is detected inside the keychain.

It's all explained in the documentation:
https://github.com/lupidan/apple-signin-unity#implement-sign-in-with-apple

Closing
