### ISSUE TITLE
iOS 15.7 will not fall back to Passcode when Face ID fails

### ISSUE THREAD

**Issue by DaveOak** [lupidan/apple-signin-unity#154]
Prior to 15.7, after Face ID fails an option to use Passcode instead was offered. Following the 15.7 update, this no longer occurs and it is not possible to sign in following a failed Face ID.

**Comment by lupidan** [comment]
The native window that performs the login is a built-in iOS window. We can not modify it's behaviour if it does not work to your liking.

If you think it's a bug, you should report it directly to Apple.

Closing
