### ISSUE TITLE
I have a question about stringUser {get;} on ICredential interface.

### ISSUE THREAD

**Issue by khj1998** [lupidan/apple-signin-unity#158]
I logged in to the apple through quick login, and I was able to get the user string value of the ICredential interface from the callback that authentication was successful .It was confirmed that it was formed in the form of xxxxx.xxxxxxxxxx.xxxxx
Is this a JWT token?
And does this string token have an expiration date?

**Comment by lupidan** [comment]
This is not an issue, it's a question.

No,[ it's just a user id string](https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Interfaces/ICredential.cs#L8)

Try casting it to an IAppleIDCredential to [expose the JWT token](https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Interfaces/IAppleIDCredential.cs#L10).

It's all in the [documentation](https://github.com/lupidan/apple-signin-unity#perform-sign-in-with-apple).

Closing
