### ISSUE TITLE
this plugin remove PushNotification capability

### ISSUE THREAD

**Issue by hoainam1593** [lupidan/apple-signin-unity#162]
I integrated Mobile Notification plugin and it added PushNotification capability.
But after I integrate this plugin, it removed that capability
Why it happen?

**Comment by lupidan** [comment]
This plugin does not remove any capability. You are probably doing your postprocess incorrectly and replacing the main "Info.plist" with a different one with a different name.

Closing

**Comment by hoainam1593** [comment]
> This plugin does not remove any capability. You are probably doing your postprocess incorrectly and replacing the main "Info.plist" with a different one with a different name.
> 
> Closing

let I clarify my scenario:
1. create empty project
2. add plugin: https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.4/manual/iOS.html
3. build ios, that plugin add PushNotification capability
4. add your plugin
5. build ios and PushNotification capability vanish
so I believe your plugin make PushNotification capability disappear

**Comment by lupidan** [comment]
Let me clarify my answer:

**Nowhere** in the code we remove a capability or any "Info.plist" file.
You probably need to adapt your post processing to use the same "Info.plist" file as the Mobile Notifications one.
