### ISSUE TITLE
ErrorCode 1001

### ISSUE THREAD

**Issue by reezoobose** [lupidan/apple-signin-unity#166]
Not Sure What Causing it :

` nw_endpoint_copy_association_with_evaluator nw_context_caches_are_shared(context (<nw_context com.apple.CFNetwork.NSURLSession.{XXX47993-2CA2-XXXX-8DBE-BB45XXX10824}{(null)}{Y}{2} (private)>), endpoint->context (<nw_context Default Network Context (private)>)) is false`

`[Authorization] ASAuthorizationController credential request failed with error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1001 "(null)"`

**Comment by lupidan** [comment]
Not an issue.

That error happens whenever the user cancels.

https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Enums/AuthorizationErrorCode.cs#L16
