### ISSUE TITLE
Add framework with postprocessing build

### ISSUE THREAD

**Issue by RomainBitard** [lupidan/apple-signin-unity#170]
Hey, the instructions are awesome I really like the post processing scripts because I only use Unity cloud build.
So my question is how can I do that for this step 

"    You need to import the AuthenticationServices.framework library in the Build Phases->Link Binary with Libraries. If you are targeting older iOS versions, mark the library as Optional.

    For Unity 2019.3 onwards, add it to the UnityFramework target

    For previous Unity versions, add it to the main Unity-iPhone target"

Is it possible ? I believe so but I'm not good at post processing scripts if anyone knows that'd be awesome !

**Comment by lupidan** [comment]
There is documentation on how to do it programatically, please read it.

https://github.com/lupidan/apple-signin-unity#programmatic-setup-with-a-script

Closing
