### ISSUE TITLE
appleAuthManager.GetCredentialState aways returning error

### ISSUE THREAD

**Issue by lmgualandi** [lupidan/apple-signin-unity#171]
appleAuthManager.LoginWithAppleId is passing without an error but then when appleAuthManager.GetCredentialState is called it gives an error with the following description:

`The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)`

Also in xCode there appears this log:

`Credential State request returned with error: Error Domain=AKAuthenticationError Code=-7091 "(null)"`

I couldn't find out what this error code means (7091)

What I did:
-Added sign in capability in Xcode and checked the entitlements file
-Added AuthenticationServices.framework in Xcode
-Activated Apple signin in the app id in the developer portal and made a new provisioning profile with it
-Configured Sign in with Apple for Email Communication in the developer portal

Any help appreciated

**Comment by lupidan** [comment]
The plugin just gives back whatever Apple returns from the servers. In this case, an [Unknown](https://github.com/lupidan/apple-signin-unity/blob/e39981bca07f08f068231f651e1e8d0f69397222/AppleAuth/Enums/AuthorizationErrorCode.cs#L11) error.

Only thing I can suggest is to check the account that is logged in the iPhone, should be a legit one, not a sandbox one, or one that needs to accept some more Terms of Service or something.

Your best bet is to ask directly in the Apple forums to get a more knowledgeable answer.

**Comment by UmarBhatPlaystrom** [comment]
For anyone experiencing the same issue check out this thread first: https://github.com/lupidan/apple-signin-unity/issues/40
