### ISSUE TITLE
AKAuthenticationError Code=-7003 "(null)" 

### ISSUE THREAD

**Issue by jijiale520** [lupidan/apple-signin-unity#173]
hello

I tested with the example project you provided with error code -7003. I made sure that the valid certificate and login service were configured in the Apple development background, and the corresponding Bundle Identifier was changed when the package was exported.

I hope that the author can give hints and solutions after seeing this problem, I would be very grateful.

Attach full log:```Authorization failed: Error Domain=AKAuthenticationError Code=-7003 "(null)" UserInfo={AKClientBundleID=com.xxx.xxx}```

**Comment by yoreleihee** [comment]
Was this issue resolved?
