### ISSUE TITLE
I have an inquiry from Iphone12 (IOS 16.6).

### ISSUE THREAD

**Issue by sysdot** [lupidan/apple-signin-unity#174]
I have an inquiry from Iphone12 (IOS 16.6).
1. Even after the initial login, I constantly ask for a password every time I log in, and I keep asking for a password even though the token has not expired. How do I avoid requiring a password after my initial login?

2. When QuickLogin is called, the keyboard does not print out.

**Comment by sysdot** [comment]
I think First issue only occurs in my project.
Is there a project setting that I missed?
I don't want to enter my password every time.

If I use GetCredentialState, I need data to send to Firebase.
Firebase fails authentication with idToken, authCode, and rawNonce acquired from an existing login.

**Comment by lupidan** [comment]
The identification flow is shown here. Please familiarize with it:
https://github.com/lupidan/apple-signin-unity#implement-sign-in-with-apple

After login in, if you have an apple user ID available, you have an API method to get the credential state for the specific apple user id.

And we do not give support to Firebase in this repository.
