### ISSUE TITLE
Issue with native pop-up orientation

### ISSUE THREAD

**Issue by aleksey2403** [lupidan/apple-signin-unity#175]
Hi!

I am getting an issue with native pop-up orientation, screenshot attached.

![AppleSignInPopUp](https://github.com/lupidan/apple-signin-unity/assets/13906343/cc1236d9-e918-41bc-bb60-3178d5814c9d)

The pop up should have been rendered in portrait, but instead its container is rotated so it does not cover nor fits the screen. 
It does not happen all the time. Our app is landscape only.
Device: iPhone 14 pro.

Short video is below:
https://drive.google.com/file/d/1_RXzVLTy_SWj5NPr24cuT8YEi4z6feAB/view?usp=sharing

Best regards,
Oleksii

**Comment by mdn0420** [comment]
I'm experiencing a similar issue. It seems to happen for us if the pop-up get's displayed a 2nd time during the app session.

Unity 2021.3.16f1
Device: iPhone 12 Pro Max, iOS 16.6

**Comment by lupidan** [comment]
Addressed in the FAQ:

https://github.com/lupidan/apple-signin-unity#does-it-support-landscape-orientations
