### ISSUE TITLE
How to get identity token from second login without asking the user to sign in again?

### ISSUE THREAD

**Issue by shinronit** [lupidan/apple-signin-unity#177]
I am using playfab and it requires apple identity token in order to sign in. As far as I know identity token expires every 24 hours. So how do I get a new identity token without giving a apple sign in prompt to user? Most games do auto sign in from second login but I am not sure how to achieve it. If I can get identity token without apple sign in popup I can just send it to playfab and login.

**Comment by lupidan** [comment]
The only way to get an Identity Token from Apple is to perform a LoginWithApple action (or a quick login if the user logged in with apple in the past) which requires a User interaction to enter credentials, fingerprint or whatever...

I don't know how Playfab works but I would assume that the Apple identity token is used once to create/log in a Playfab user, and stays logged in until the app is deleted.

Please search in the Playfab documentation, or check with Playfab support.
