### ISSUE TITLE
애플 로그인에서 자기가 사용하고 있는 핸드폰 번호,이름을 가져올 수 있나요?

### ISSUE THREAD

**Issue by casphoe** [lupidan/apple-signin-unity#183]
LoginOptions 라는 enum 변수에서 IncludeEmail 와 비슷하게 IncludePhone = 1 << 2, 로 만들어서 핸드폰 정보를 가지고 와야하는 건가요?

**Comment by lupidan** [comment]
Please write your issues in English.
