### ISSUE TITLE
The type or namespace name 'AppleAuth' could not be found

### ISSUE THREAD

**Issue by ChurikiTenna** [lupidan/apple-signin-unity#185]
I installed the plugin following [this](https://github.com/lupidan/apple-signin-unity#install-via-git-url).
It fails with `The type or namespace name 'AppleAuth' could not be found (are you missing a using directive or an assembly reference?).`
and
`'ProjectCapabilityManager' does not contain a definition for 'AddSignInWithAppleWithCompatibility'`

<img width="1384" alt="スクリーンショット 2023-11-09 11 20 45" src="https://github.com/lupidan/apple-signin-unity/assets/52132649/2f42135d-022f-40a1-8e9a-45de9ebafd44">
<img width="759" alt="スクリーンショット 2023-11-09 11 20 19" src="https://github.com/lupidan/apple-signin-unity/assets/52132649/7554d6cd-c841-4c07-a693-43500c7d5503">
<img width="904" alt="スクリーンショット 2023-11-09 11 58 02" src="https://github.com/lupidan/apple-signin-unity/assets/52132649/6db4a7ff-f128-4594-b5fc-7d5216bd30ab">

I am new to Unity, so pardon me for the fundamental question.

**Comment by andreyfaraponov** [comment]
Hi, did you have added Assembly reference to Assembly where located SignInWithApplePostProcessor.cs?

**Comment by ChurikiTenna** [comment]
I re-installed the plugin with PackageManager, then `'AppAuth' cloud not be found` error disappeared.

Where can I find the Assembly reference? I don't even see apple-signing-unity folder in my Asset..
<img width="319" alt="スクリーンショット 2023-11-10 9 54 04" src="https://github.com/lupidan/apple-signin-unity/assets/52132649/21a967ef-4827-464f-9ee9-784b24b9d7bb">

**Comment by lupidan** [comment]
Since "reinstalling" worked, I am closing this ticket.
Package code from Github in manifest files is read-only, and it's not stored in your Assets folder.
