### ISSUE TITLE
Exception building for Mac

### ISSUE THREAD

**Issue by futer24** [lupidan/apple-signin-unity#189]
Hello

I have the following exception building for Mac:

Unity 2021.3.9f1
Mac OS Ventura 13.0.1

AppleAuthMacosPostprocessorHelper: Error while fixing MacOSAppleAuthManager.bundle bundle identifier :: 
Could not find a part of the path "/Volumes/Crucial X6/Builds/3b/3b.app/Contents/Plugins/MacOSAppleAuthManager.bundle/Contents/Info.plist".
UnityEngine.Debug:LogError (object)
AppleAuth.Editor.AppleAuthMacosPostprocessorHelper:FixManagerBundleIdentifier (UnityEditor.BuildTarget,string) (at Assets/AppleSignInUnity/AppleAuth/Editor/AppleAuthMacosPostprocessorHelper.cs:43)
AppleAuthSample.Editor.SignInWithApplePostprocessor:OnPostProcessBuild (UnityEditor.BuildTarget,string) (at Assets/AppleSignInUnity/AppleAuthSample/Editor/SignInWithApplePostprocessor.cs:40)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

Thanks!

**Comment by futer24** [comment]
I just copied the bundle into the required subfolder and always get the following line in the Unity logs:

Sign in with Apple failed Unknown AppleAuth.Native.AppleError

**Comment by lupidan** [comment]
> Sign in with Apple failed Unknown AppleAuth.Native.AppleError

The error comes as Apple reports it. I suggest double checking the setup for Sign In With Apple is correct on Apple´s developer website, as well as checking what account is trying to use to login (not a Sandbox account f.ex.)

Otherwise, I suggest just going to  Apple´s forums and ask for help there.
