### ISSUE TITLE
Nonce question

### ISSUE THREAD

**Issue by fmorenogg** [lupidan/apple-signin-unity#19]
Hi lupidan,

I have a question regarding the nonce token generation and retrival. Due to the implementation of Firebase I have to send the token ID and the **raw** nonce to be able to authenticate in firebase with Sign in with apple provider.
I can get identity token from your IAppleIDCredential  interface under IdentityToken property, but I'm having problems to get the nonce. In the same IAppleIDCredential interface there is a State property that the comment states: 

`An arbitrary string that your app provided to the request that generated the credential.` 

I think this is the nonce, but it's always null when I get the credential. There is any way to get the raw nonce token?

Thanks for your great work, It saved us a great deal of time.

Gracias!

**Comment by lupidan** [comment]
Nonce support for requests is not available in v1.0.0.
We are adding support for it on the future v1.1.0. Right now the code for it is available on the canary branch.
https://github.com/lupidan/apple-signin-unity/tree/canary

This was the pull request for it, merged in canary already
https://github.com/lupidan/apple-signin-unity/pull/18

There is one more thing that we would like to add to the new version, to simplify the callback handling. In the meantime you can use the canary branch.

I'm leaving this open till we release v1.1.0 👍 

Hope that helps

**Comment by fmorenogg** [comment]
> 
> 
> Nonce support for requests is not available in v1.0.0.
> We are adding support for it on the future v1.1.0. Right now the code for it is available on the canary branch.
> https://github.com/lupidan/apple-signin-unity/tree/canary
> 
> This was the pull request for it, merged in canary already
> #18
> 
> There is one more thing that we would like to add to the new version, to simplify the callback handling. In the meantime you can use the canary branch.
> 
> I'm leaving this open till we release v1.1.0 👍
> 
> Hope that helps

Great! Thanks for the insight of the project roadmap. In the meantime we will use the canary branch.

Thanks!

**Comment by lupidan** [comment]
@fmorenogg Version 1.1.0 is published in master
You can find an easy migration article here.

https://github.com/lupidan/apple-signin-unity/wiki/Migration-guides

Thanks again for the ticket 👍 
Closing this now
