### ISSUE TITLE
Regarding the status of Privacy Manifest compatibility. 

### ISSUE THREAD

**Issue by k0uhe1D** [lupidan/apple-signin-unity#190]
We are utilizing your SDK for the implementation of SigninWithApple in our app. 
However, it appears that the latest version, v1.4.3, does not support PrivacyManifest. 

If there are plans to support this, we would like to know when it is expected to be supported (an estimated time frame is fine). 
If it is possible to provide this information, please let us know. 

Thank you for your cooperation.

https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by lupidan** [comment]
- For iOS/tvOS builds, the code is included inside your Unity Framework (no bundled `.framework` that requires signing)
- The plugin code does not use any of the APIs Apple does require to have reason for usage.
- The plugin does not send the SIWA data to any servers, or store it anywhere else, it just passes the information to the C# managed code. Whatever tracking you do with that information is up to your app/game.

So, this plugin does not need to provide any Privacy Manifest.
