### ISSUE TITLE
How can i get the sign in informations after app is removed and re-installed ??

### ISSUE THREAD

**Issue by sana2024** [lupidan/apple-signin-unity#193]
hello, i've been using this plugin for a while and everything is working fine,

first login i get the user informations (username, email .. etc)
first i store this on device cache and then i create an account on my database with these information,
every other time i try to login i get these informations from cache and query it to my database based on the apple id email, this way i get the full information from the database.

here is the problem when a user uninstalls my app or try to login with another device, this cache will be removed and for that the app needs to rely on apple sign in again to query to the database but this time apple doesn't give me anything to work on, so what am i supposed to do here ??? 
i tried to login with the other credentials instead of email but they all change so there is no way to get back the account from a credential that changes or it's temporary. 
is there anything i can rely on ????

this is the flow:

1. register:  apple siginin dialog ---> cache -----> database
2. login : cache ----> database 

by the way i'm using Nakama as my server and by typing the token in Authenticationwithapple t does not work so i have to rely on email login.

**Comment by lupidan** [comment]
https://github.com/lupidan/apple-signin-unity?tab=readme-ov-file#quick-login
