### ISSUE TITLE
Can't be opened on macos app

### ISSUE THREAD

**Issue by wbb21230** [lupidan/apple-signin-unity#194]
![image](https://github.com/lupidan/apple-signin-unity/assets/49426786/050b1dee-e5df-492a-8326-29ea07f7af35)
我按照你的方式签名但是怎么都过不了 ，出现应用程序无法打开，
这是我的entitlements文件
![image](https://github.com/lupidan/apple-signin-unity/assets/49426786/44454361-7f66-4f46-9077-39d9e5add296)
错误log：
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600003768150 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
![image](https://github.com/lupidan/apple-signin-unity/assets/49426786/84392ddb-a8ee-4877-9547-0ff03ebeeed7)

**Comment by lupidan** [comment]
Please open issues in English.
