### ISSUE TITLE
Error with unity 2023.2.5f1

### ISSUE THREAD

**Issue by sameehj** [lupidan/apple-signin-unity#195]
I got this error with unity 2023.2.5f1

Exception: Can't Add Sign In With Apple programatically in this Unity version

Temporary FIX:
Comment out the code in:
AddSignInWithAppleWithCompatibility(), it is not needed.

**Comment by lupidan** [comment]
https://github.com/lupidan/apple-signin-unity/releases/tag/v1.4.3
