### ISSUE TITLE
Pressing "Close" when user is not signed in to settings returns "Unknown" error code

### ISSUE THREAD

**Issue by urface333** [lupidan/apple-signin-unity#20]
Pressing the "Close" button in the screenshot below returns an "Unknown" AuthorizationErrorCode rather than "Canceled". This happens when the user is not signed in to their Apple ID on phone settings. Is that to be expected?

I see the following error message in the logs: 
   Authorization failed: Error Domain=AKAuthenticationError Code=-7022 "(null)" UserInfo={AKClientBundleID=...}

![IMG_0003](https://user-images.githubusercontent.com/61025803/74468963-973e1580-4e50-11ea-807b-ac28c06617a9.PNG)

Also, thank you for making this plugin; it's much appreciated!

**Comment by lupidan** [comment]
This plugin returns the error as it comes from Apple's SDK. In that particular case, the SDK returns Unknown error when the user clicks cancel. This is not an issue. It´s just how Apple decided it will work.

This is the error returned when clickin Cancel in that particular scenario
![Captura de pantalla 2020-02-16 a las 20 27 13](https://user-images.githubusercontent.com/1314521/74610334-09398780-50fb-11ea-90b4-8e4173f958d8.png)

The error code is 1000, which is the equivalent of an Unknown ASAuthorizationError
https://developer.apple.com/documentation/authenticationservices/asauthorizationerror/asauthorizationerrorunknown?language=objc
