### ISSUE TITLE
AppleAuthManager Update function error?

### ISSUE THREAD

**Issue by toptomsk** [lupidan/apple-signin-unity#201]
Hi, I have face a problem
When i run project on device, the error appear right in the line:

`this._appleAuthManager.Update();`

The error say: NullReferenceException: Object reference not set to an instance of object

What wrong with function update() here ? anyone know how to fix this? please help me.
Thanks

**Comment by MrVeit** [comment]
Hi, are you checking this component for null as stated in the documentation?

**Comment by toptomsk** [comment]
> Hi, are you checking this component for null as stated in the documentation? Try it without specifying `this`
Yes, im checking null for sure.

By the way, When I tried to reimport package 2-3 times and...it''s working suddenlly. No idea about what's going on this error.
