### ISSUE TITLE
Email empty when signin

### ISSUE THREAD

**Issue by XaguStudios** [lupidan/apple-signin-unity#205]
We thought the fault was on our side because we were not asking for the email scope in args but still getting empty mail even revoking credentials on our test device.

Cant get email, string comes empty everytime, revoking credentials has no effect.

`var loginArgs = new AppleAuthLoginArgs(LoginOptions.IncludeEmail);

        this.appleAuthManager.LoginWithAppleId(
            loginArgs,
            credential =>
            {
                // Obtained credential, cast it to IAppleIDCredential
                IAppleIDCredential appleIdCredential = credential as IAppleIDCredential;
                if (appleIdCredential != null)
                {
                    // Apple User ID
                    // You should save the user ID somewhere in the device
                    Debug.Log("First Register");
                    Debug.Log("Apple ID: " + appleIdCredential.User + " appleMail: " + appleIdCredential.Email);
                    string user = appleIdCredential.User;
                    string appleMail = appleIdCredential.Email;
                    PlayerPrefs.SetString("AppleID", user);
                    PlayerPrefs.SetString("AppleMail", appleMail);`

No errors and appleIDCredential not null but we always get an empty string.

Any clue?
Thanks!

**Comment by lupidan** [comment]
https://github.com/lupidan/apple-signin-unity?tab=readme-ov-file#i-am-not-getting-a-full-name-or-an-email-even-though-i-am-requesting-them-in-the-loginwithappleid-call

Please check the README
