### ISSUE TITLE
Question: Where can I find all IAppleError error codes?

### ISSUE THREAD

**Issue by maxgmer** [lupidan/apple-signin-unity#206]
Where can I find all sign-in error codes for proper handling?

Also, would be wonderful if `IAppleError.Code` was an enum instead of an `int`. Would've been much more intuitive and enums can still be mapped to `int` of error codes.

You can answer this question in FAQ of the plugin doc, by the way, I think this would be useful to other people as well.

Is this list exhaustive?
https://developer.apple.com/documentation/authenticationservices/asauthorizationerror/code

**Comment by lupidan** [comment]
Yes
