### ISSUE TITLE
AddSignInWithAppleWithCompatibility is missing

### ISSUE THREAD

**Issue by drew-fc** [lupidan/apple-signin-unity#207]
I am following the readme, but when trying to setup the post processor script, I get an error that no method with name "AddSignInWithAppleWithCompatibility" exists on the ProjectCapabilityManager.

It does have "AddSignInWithApple" which is parameterless. Maybe it got updated and the docs are old?

Appreciate your help

**Comment by lupidan** [comment]
>It does have "AddSignInWithApple" which is parameterless. Maybe it got updated and the docs are old?

No

`AddSignInWithApple` is a method provided by Unity that adds the `AuthenticationServices.framework` as Mandatory, making it crash in older iOS versions

`AddSignInWithAppleWithCompatibility` is an extension method provided by this plugin, that adds the `AuthenticationServices.framework` as Optional, so it does not crash in older iOS devices

Check your namespaces and assembly definitions to ensure:
- You are adding `using AppleAuth.Editor;`
- The assembly containing the usage of this method has a reference to the assembly `AppleAuth.Editor`

**Comment by silleknarf** [comment]
I had the same issue and I was able to resolve it by putting an `#if UNITY_IOS` preprocessor directive at the top of the script and an `#endif` at the bottom.
