### ISSUE TITLE
Using with firebase auth?

### ISSUE THREAD

**Issue by matthewmck92** [lupidan/apple-signin-unity#26]
Hello,

Im trying to use your plugin with the firebase auth plugin. In order to create a firebase credential I need what they call an idToken as a string and an access token also as a string. Any idea how I could generate these from your plugin? Looking at the IApplIDCredential interface there are byte arrays called IdentityToken and  AuthorizationCode, could these be what I need once in string format?

Cheers Macca.

**Comment by matthewmck92** [comment]
Found the nonce option!

**Comment by lupidan** [comment]
Hi, nice that you found it.

I started a Wiki page on how this plugin could work together with Firebase. Feel free to take a look. I still need to test it out with an actual Firebase service though. But the theory is there.

https://github.com/lupidan/apple-signin-unity/wiki/Sign-in-with-Apple-Unity-Plugin:-Working-with-Firebase

**Comment by lupidan** [comment]
@matthewmck92 Nice that you found it.

I started a Wiki page on how this plugin could work together with Firebase. Feel free to take a look. I still need to test it out with an actual Firebase service though. But the theory is there.

https://github.com/lupidan/apple-signin-unity/wiki/Sign-in-with-Apple-Unity-Plugin:-Working-with-Firebase
