### ISSUE TITLE
How to get nonce?

### ISSUE THREAD

**Issue by reysantana** [lupidan/apple-signin-unity#27]
Hello

I am trying to login to the firebase using credentials.
Code:
```
var loginArgs = new AppleAuthLoginArgs(AppleAuth.Enums.LoginOptions.IncludeEmail | AppleAuth.Enums.LoginOptions.IncludeFullName);

appleAuthManager.LoginWithAppleId(
loginArgs,
credentials =>
{
var appleIdCredential = credentials as IAppleIDCredential;
if (appleIdCredential == null)
{
return;
}

string rawNonce = loginArgs.Nonce;

string authCode = Encoding.UTF8.GetString(appleIdCredential.AuthorizationCode);

Credential credential = OAuthProvider.GetCredential("apple.com", Encoding.UTF8.GetString(appleIdCredential.IdentityToken), rawNonce, authCode);

auth.SignInWithCredentialAsync(credential).ContinueWith(task =>
{
if (task.IsCanceled)
{
Debug.LogError("SignInWithCredentialAsync was canceled.");
return;
}
if (task.IsFaulted)
{
Debug.LogError("SignInWithCredentialAsync encountered an error: " + task.Exception);
return;
}

user = auth.CurrentUser;

Debug.LogFormat("User signed in successfully: {0} ({1})",
user.DisplayName, user.UserId);
});
},
error =>
{
return;
});
```
Error:
```
ApplicationException: provider_id && id_token && raw_nonce
```
I think I am getting wrong rawNonce from the code below.
Please help me to fix this issue.
Thanks.

**Comment by lupidan** [comment]
Hi

You are not creating any nonce at all...

For supporting Sign in with Apple in Firebase you need to:
1. Create a RAW NONCE (random and cryptographically secure) => This is what you will send to Firebase
2. Create a SHA256 of the previous RAW NONCE, and use it when creating the AppleAuthLoginArgs => This is what you will send to Apple when requesting a login.

There is a full manual available in the Wiki. Please read it:
https://github.com/lupidan/apple-signin-unity/wiki/Sign-in-with-Apple-Unity-Plugin:-Working-with-Firebase

**Comment by faizanophobia** [comment]
Hello
I am facing the same issue even after providing nonce and rawnonce, throws the same error in unity and Xcode.
ApplicationException: provider_id && id_token && raw_nonce
Firebase.Auth.OAuthProvider.GetCredential (System.String providerId, System.String idToken, System.String rawNonce, System.String accessToken) (at Z:/tmp/tmp.NyNkO6ATTa/firebase/auth/client/unity/proxy/OAuthProvider.cs:36)

**Comment by faizanophobia** [comment]
> Hello
> 
> I am trying to login to the firebase using credentials.
> Code:
> 
> ```
> var loginArgs = new AppleAuthLoginArgs(AppleAuth.Enums.LoginOptions.IncludeEmail | AppleAuth.Enums.LoginOptions.IncludeFullName);
> 
> appleAuthManager.LoginWithAppleId(
> loginArgs,
> credentials =>
> {
> var appleIdCredential = credentials as IAppleIDCredential;
> if (appleIdCredential == null)
> {
> return;
> }
> 
> string rawNonce = loginArgs.Nonce;
> 
> string authCode = Encoding.UTF8.GetString(appleIdCredential.AuthorizationCode);
> 
> Credential credential = OAuthProvider.GetCredential("apple.com", Encoding.UTF8.GetString(appleIdCredential.IdentityToken), rawNonce, authCode);
> 
> auth.SignInWithCredentialAsync(credential).ContinueWith(task =>
> {
> if (task.IsCanceled)
> {
> Debug.LogError("SignInWithCredentialAsync was canceled.");
> return;
> }
> if (task.IsFaulted)
> {
> Debug.LogError("SignInWithCredentialAsync encountered an error: " + task.Exception);
> return;
> }
> 
> user = auth.CurrentUser;
> 
> Debug.LogFormat("User signed in successfully: {0} ({1})",
> user.DisplayName, user.UserId);
> });
> },
> error =>
> {
> return;
> });
> ```
> 
> Error:
> 
> ```
> ApplicationException: provider_id && id_token && raw_nonce
> ```
> 
> I think I am getting wrong rawNonce from the code below.
> Please help me to fix this issue.
> Thanks.

Where you able to fix this?
Thanks!

**Comment by faizanophobia** [comment]
> Hello
> 
> I am trying to login to the firebase using credentials.
> Code:
> 
> ```
> var loginArgs = new AppleAuthLoginArgs(AppleAuth.Enums.LoginOptions.IncludeEmail | AppleAuth.Enums.LoginOptions.IncludeFullName);
> 
> appleAuthManager.LoginWithAppleId(
> loginArgs,
> credentials =>
> {
> var appleIdCredential = credentials as IAppleIDCredential;
> if (appleIdCredential == null)
> {
> return;
> }
> 
> string rawNonce = loginArgs.Nonce;
> 
> string authCode = Encoding.UTF8.GetString(appleIdCredential.AuthorizationCode);
> 
> Credential credential = OAuthProvider.GetCredential("apple.com", Encoding.UTF8.GetString(appleIdCredential.IdentityToken), rawNonce, authCode);
> 
> auth.SignInWithCredentialAsync(credential).ContinueWith(task =>
> {
> if (task.IsCanceled)
> {
> Debug.LogError("SignInWithCredentialAsync was canceled.");
> return;
> }
> if (task.IsFaulted)
> {
> Debug.LogError("SignInWithCredentialAsync encountered an error: " + task.Exception);
> return;
> }
> 
> user = auth.CurrentUser;
> 
> Debug.LogFormat("User signed in successfully: {0} ({1})",
> user.DisplayName, user.UserId);
> });
> },
> error =>
> {
> return;
> });
> ```
> 
> Error:
> 
> ```
> ApplicationException: provider_id && id_token && raw_nonce
> ```
> 
> I think I am getting wrong rawNonce from the code below.
> Please help me to fix this issue.
> Thanks.

Were you able to fix this?Any help would be appreciated
Thanks!
