### ISSUE TITLE
XCode Build failed - arm64 function not 4-byte aligned

### ISSUE THREAD

**Issue by dalkia** [lupidan/apple-signin-unity#28]
Hi! Im trying to build the project in Xcode. Ive done all manual configuration, but it keeps failing here:

![WhatsApp Image 2020-04-24 at 8 52 06 PM](https://user-images.githubusercontent.com/1999557/80265357-b1287f80-866d-11ea-8975-ea39596975cb.jpeg)

Anyone got the same error??

**Comment by lupidan** [comment]
The build is failing to link the essential `AuthorizationServices.framework`
If you want to support iOS 13 capabilities like this, you need to build with the latest Xcode version.
- What Xcode version are you running?

https://github.com/lupidan/apple-signin-unity#plugin-setup
- Did you setup the plugin correctly? If you did you should have the specific entry in the entitlements file, and the `AuthorizationServices.framework` included as Optional

**Comment by dalkia** [comment]
No luck...I updated to Catalina and Im using the XCode 11.4.1. And is still failling in the same point

**Comment by lupidan** [comment]
Please double check the `AuthorizationServices.framework` is in the Build Phases as "Optional"

![Screenshot 2020-04-26 at 0 18 43](https://user-images.githubusercontent.com/1314521/80291236-b0b6e400-8754-11ea-82db-efbf0d655af5.png)

If it´s not there, you are not doing the setup correctly.

**Comment by dalkia** [comment]
Hey! Yes, I had the AuthorizationServices. 

None the less, I didnt have all the others binaries you mention, which I had present in the UnityFrameworkk target. So, i channged the target and added the service in the BuildPhases of the UnityFramework target. And it worked!

Thanks for everything

**Comment by lupidan** [comment]
Hi @dalkia, just a heads up , we identified the linking error issue with Unity 2019.3, and it was fixed on v1.2.0

**Comment by dalkia** [comment]
Thanks for the heads up! I will try it out

**Comment by Waqax19** [comment]
<img width="1195" alt="Screen Shot 2020-08-23 at 11 46 55 AM" src="https://user-images.githubusercontent.com/48880127/91024104-bf74b100-e5f7-11ea-82ef-1085e3287e24.png">
I am getting same undefined error, but with webrtc !! if you know which framework it is missing please

**Comment by lupidan** [comment]
> <img width="1195" alt="Screen Shot 2020-08-23 at 11 46 55 AM" src="https://user-images.githubusercontent.com/48880127/91024104-bf74b100-e5f7-11ea-82ef-1085e3287e24.png">
> I am getting same undefined error, but with webrtc !! if you know which framework it is missing please

This plugin does not use that technology, and the build error seems related to the libiphone-lib.a library. 

Seek help in Unity forums or unity support, your build error is unrelated to this plugin.

**Comment by Waqax19** [comment]
okay thanks
