### ISSUE TITLE
'PBXProject.GetUnityTargetName()' is obsolete in Unity 2019.3

### ISSUE THREAD

**Issue by Kezzo** [lupidan/apple-signin-unity#32]
Getting the following error after updating to Unity 2019.3

> Assets/Scripts/Integrations/SignInWithApplePostprocessor.cs(16,94): error CS0619: 'PBXProject.GetUnityTargetName()' is obsolete: 'This function is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead of calling to TargetGuidByName(GetUnityTargetName()).'

**Comment by lupidan** [comment]
Hey, thanks for the report @Kezzo 
Could you specify the exact Unity 2019.3 version? That will help identify the scenario and make a fix.

**Comment by Kezzo** [comment]
I'm using Unity 2019.3.13f1.

The error is happening when using the entitlements script in the readme.

**Comment by Kezzo** [comment]
I added a pull request that updates the readme and includes a working solution for Unity 2019.3 and up.
https://github.com/lupidan/apple-signin-unity/pull/33

**Comment by lupidan** [comment]
You need to adapt your Post Processing build for Unity 2019.3.
There is a tentative solution in the example:
https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuthSampleProject/Assets/AppleAuthSample/Editor/SignInWithApplePostprocessor.cs

This wasn't really referenced in the `README.md` document, so I guess we could add the information there

**Comment by Kezzo** [comment]
Oh I guess we pressed send at the same time! Seems like we got the same solution! ;)

**Comment by lupidan** [comment]
Documentation enhancement approved and merged.
Thanks for the contribution @Kezzo 👍

**Comment by lupidan** [comment]
Hi @Kezzo, the issue was a bit more convoluted than we thought. A new version v1.2.0 was released that includes a fix for the PostProcessing on Unity 2019.3

Basically, the entitlements need to be added to the main target, and the Framework need to be added to the UnityFramework target.

Please check the updated documentation.

**Comment by Kezzo** [comment]
Okay! Thanks for the update!
