### ISSUE TITLE
How to add SignInWithApple Capability below Unity2019?

### ISSUE THREAD

**Issue by roclau0102** [lupidan/apple-signin-unity#38]
ProjectCapabilityManager has no method AddSignInWithAppleWithCompatibility() in Unity2017 or Unity2018. How could I add this capability below Unity2019 programmatic?

**Comment by lupidan** [comment]
`AddSignInWithAppleWithCompatibility` is an **extension method** provided by the plugin.
You need to include the correct namespace to see it.

```
using AppleAuth.Editor;
```

**Comment by roclau0102** [comment]
Ye, I found it, thanks a lot bro
