### ISSUE TITLE
Does it work on MacOS?

### ISSUE THREAD

**Issue by masteranza** [lupidan/apple-signin-unity#4]
Before all else let me apologize for asking this question here as it's clearly not an issue, however I couldn't find any info on that and I hesitate to update my project. I'm guessing that because unity doesn't generate an XCode project for Mac. Am I right?

**Comment by lupidan** [comment]
This plugin does not currently support OSX. Probably some code can be reused for it though. (define clauses and availability checks have OSX in consideration).
We can leave the issue open for discussion on how to do it. You choose.

**Comment by ledvinam** [comment]
Hi lupidan, we need this for macOS as well. Can we work on it together? Should be simple since the code should be the same for macOS. Can we connect discord or skype? Thanks, Marek.

**Comment by lupidan** [comment]
Hi!
I started some development on a few weeks ago in this branch:
https://github.com/lupidan/apple-signin-unity/tree/feature/macosxSupport

But unfortunately, I can´t really test it because I don´t have Catalina just yet. So I stopped work on it for now. But the main idea was to have a separate Xcode library project, reusing the source files of the current iOS/tvOS solution. And readapt the code for OSX.

I made my email visible on my Github profile, feel free to reach me there.

**Comment by lupidan** [comment]
I was finally able to get my hands in a mac with Catalina, and I have been experimenting a bit during the weekend...

I made an Xcode project for a Mac App with my slightly altered code to support MacOS, and I was able to get the Sign In With Apple prompt and the functionality was working the same way as iOS (Login, Get Credential State and Quick login). So in that sense, it seems like the code should work just fine!

However, I am having a **really though** time in regards to signing the Unity app with my developer certificate.

Currently I am trying to sign the new builds with my "Apple Developer" certificate, and I am including the correct provisioning profile into the build as "embedded.provisioningprofile"

Signing the app with two small entitlements required by Unity it´s OK, I am still able to run the signed app in my mac device (which is included in that provisioning profile).

However, **the moment I try adding the Sign In With Apple entitlement** and re-codesign the app with my Developer certificate, the app won´t launch anymore at all...

If anyone has **any clue** regarding this, on how to sign a Mac OS build to enable Sign In With Apple, that would be great.

I´m really new to this Unity and App Signing for MacOS, so even the tiniest bit of **help** would be great.

**Comment by lupidan** [comment]
Good news!! it seems to work, after a huge codesigning hassle that is 😄 
![Screenshot 2020-04-26 at 0 09 36](https://user-images.githubusercontent.com/1314521/80291057-e3f87380-8752-11ea-9cb2-c4eec750bb5e.png)
![Screenshot 2020-04-26 at 0 10 03](https://user-images.githubusercontent.com/1314521/80291060-e529a080-8752-11ea-8f32-5cdae0bfe114.png)

**Comment by osamaraza24** [comment]
Hey , your plugin not supported unity 2019.3.5.f1 , In Xcode It gives Linking error , m i using xcode 11 above

**Comment by lupidan** [comment]
Hi @osamaraza24, could you open a new issue for that particular case, and I´ll take a look.
This thread is for discussing a macOS version of the plugin.

Thanks 👍

**Comment by lupidan** [comment]
**macOS Support was released with v1.2.0**

@osamaraza24 Even if it´s unrelated, **v1.2.0 also contains a fix for post build processing on 2019.3**. Please update and check the Readme for updated information.

Closing this.

**Comment by osamaraza24** [comment]
hey , I need help in Postprocessing script , I'm Adding SignInWithApple
Capability n Framework

**Comment by osamaraza24** [comment]
var ProjectPath = PBXProject.GetPBXProjectPath(BuildPath);
var Project = new PBXProject();
Project.ReadFromFile(ProjectPath);

var TargetName = PBXProjectExtensions.GetPBXProjectTargetName(Project);
var TargetGUID = PBXProjectExtensions.GetPBXProjectTargetGUID(Project);


var EntitlementFilename = "unity.entitlements";
var EntitlementDestination = BuildPath + "/" + TargetName + "/" +
EntitlementFilename;
File.Copy(Path.Combine(Application.dataPath, EntitlementFilename),
EntitlementDestination, true);

Project.SetBuildProperty(TargetGUID, "ENABLE_BITCODE", "NO");

Project.AddFile(TargetName + "/" + EntitlementFilename, EntitlementFilename
);
Project.AddBuildProperty(TargetGUID, "CODE_SIGN_ENTITLEMENTS", TargetName +
"/" + EntitlementFilename);
string PlistPath = BuildPath + "/Info.plist";
PlistDocument PlistDocument = new PlistDocument();
PlistDocument.ReadFromFile(PlistPath);
PlistElementDict PlistRoot = PlistDocument.root;

var PListArray = new PlistElementArray();
PListArray.AddString(DefaultAccessLevel);
PlistRoot[EntitlementsArrayKey] = PListArray;

// var CapabilityType = typeof(PBXCapabilityType);

// var ConstructorInfo = CapabilityType.GetConstructor(
// NonPublicInstanceBinding,
// null,
// new[] {typeof(string), typeof(bool), typeof(string), typeof(bool)},
// null);

// var SignInCapability = ConstructorInfo.Invoke(new object[] {
"com.apple.signin", true, AuthenticationServicesFramework, true }) as
PBXCapabilityType;
Project.AddCapability(TargetGUID, PBXCapabilityType.SignInWithApple,
EntitlementDestination, true);
Project.AddFrameworkToProject(TargetGUID, AuthenticationServicesFramework,
true);
// var manager = new
ProjectCapabilityManager(ProjectPath,EntitlementFilename, null, TargetGUID);
// manager.AddSignInWithAppleWithCompatibility(TargetGUID);
// manager.WriteToFile();
PlistRoot.SetString("NSCalendarsUsageDescription", "We currently use for
scheduling Push notifications that enables users opt-in to, for free
briefcase reminders etc");
PlistRoot.SetString("NSLocationAlwaysUsageDescription", "Uses background
location");
PlistRoot.SetString("NSLocationWhenInUseUsageDescription", "Uses background
location");

File.WriteAllText(PlistPath, PlistDocument.WriteToString());
Project.WriteToFile(ProjectPath);

Debug.Log("Completed Processing");
Debug.Log(BuildPath);

**Comment by osamaraza24** [comment]
Not able to add ,can you guide me?
