### ISSUE TITLE
Error 1000 when trying to login after app close

### ISSUE THREAD

**Issue by devingDev** [lupidan/apple-signin-unity#40]
Hi it seems I got the part working where you press the button and it logs you in initially.
When you restart it shows an error 1000 from Apple which seems to be unknown.
You can still login by pressing the sign in button again though.

I am saving the user and trying the quicklogin or whatever as per README but as I wrote I get the error code 1000.

https://hastebin.com/ranecaruwu.cs

**Comment by lupidan** [comment]
What's "restart" in this context?
Do you close the app?
Do you delete the app?
Do you revoke the Apple ID credentials in the settings menu?
Do you have a user signed in the device?
Did you sign out the user from the device?
Do you have credentials for that app in the iTunes keychain (not Apple ID credentials, but iTunes keychain credentials)?

QuickLogin attempts to get any credential stored in the iTunes keychain, or Apple ID credential silently on iOS. So... **unless Apple has changed something**... if you never revoked the Apple ID credential, and you deleted/reinstalled the app, the QuickLogin should succeed with the Apple ID user.

That´s how they implemented it in their official example. And errors are given as they come from Apple SDK. If the QuickLogin fails, with whatever error, that means you need to perform a normal Sign In.

**Comment by devingDev** [comment]
Well the way I try is like 

`if (PlayerPrefs.HasKey(AppleUserIdKey))
            {
                TryAppleLogin();
            }
            else
            {
                TryAppleQuickLogin();
            }`

So if there is an userid saved try login with that, the user id being ICredential.user !
If not it should try the quick login. I might have messed it up in my initial comment.
So actually what is failing is the 

`private void TryAppleLogin()
    {

        this.appleAuthManager.GetCredentialState(
       PlayerPrefs.GetString(AppleUserKey),
       state =>
       {
           switch (state)
           {
               case CredentialState.Authorized:
                // User ID is still valid. Login the user.
                Load();
                break;

               case CredentialState.Revoked:
                   // User ID was revoked. Go to login screen.
                   ShowFirstScreen();
                break;

               case CredentialState.NotFound:
                   // User ID was not found. Go to login screen.
                   ShowFirstScreen();
                   break;
           }
       },
       error =>
       {
           // Something went wrong
           string txt = "CATCH in onsuccess:" + error.LocalizedDescription.ToString();
           appleInfoDbg.text = txt;
           ShowFirstScreen();
       });
    }`


And I did once revoke the creds but after that I did login via sign in button just to test it and then i closed the app and it didn't log me back in next time. No deleting app, no revoking the creds in settings. A user is signed in and didn't sign out. I do not understand the last one with the keychain part this is a new app and I never used the keychain with it, not sure though.

**Comment by lupidan** [comment]
Are you testing on a real device, or in the simulator?

**Comment by devingDev** [comment]
Real device. Does apple sign in even work at all in simulator?
I build the game on Unity Cloud Build and then install via their page (AdHoc Profile).

**Comment by devingDev** [comment]
This is when I revoked and tried sign in with the button 

![ED9DB6C8-930C-4CFD-A6F6-5DEBD585A805](https://user-images.githubusercontent.com/17065236/84562853-9ca46180-ad57-11ea-9e23-e0d5bfb97ac5.jpeg)


And this is the screen when I used the sign in button once then only fully closed it and tried the sign in button again (because it throws the 1000 error instead of "logging" me back in).

![80B1728F-5A28-4D61-8A03-F0A23090A35D](https://user-images.githubusercontent.com/17065236/84562740-24d63700-ad57-11ea-8389-0351fd519fd9.jpeg)



Isnt this how I should check if the user id is still "valid" as per your readme?

**Comment by lupidan** [comment]
> Does apple sign in even work at all in simulator?

Nope, it doesn't work fully, just partially, that's why I was asking.

> Isn't this how I should check if the user id is still "valid" as per your readme?

Yup, that´s correct.

In the second screen, the LoginWithApple call automatically detects that you did Sign in With Apple in the past, that´s why it says you already authorized it.

I just did a quick test building the sample project in the latest Unity 2019.4.0f1 I provided in the source. And it works as expected.

After the user did sign in with Apple successfully, if you close and reopen the app, the `GetCredentialState` returns `Authorized`.

This is **the only report** we are getting from this. So my initial feeling is that there might be something wrong with your particular setup:
- Restart the device.
- Try a different device (is your device jailbroken¿?)
- If you can do it, try resetting the device completely and erase everything, start with a clean device.
- Check the feature is correctly setup in Apple's developer website (I believe the accounts used to sign in with Apple need 2FA f.ex.)
- If you enabled the feature very recently, wait at least a day so Apple's config settles down in the servers (yes.... I'm serious....)

If none of that works, try making a simple native project and test that out if you have the knowledge for it. You can reuse the methods in the `AppleAuthManager.m` class and link it with a single `UIButton`.

Other than that, I'm out of ideas. I would try asking for help in the Apple developer's forum, they have a section just for this feature.

https://forums.developer.apple.com/community/app-frameworks/sign-in-with-apple

**Comment by devingDev** [comment]
I mean the login does work so I am unsure what I am doing wrong with the re-login after you close and restart the app and check the saved user with "GetCredentialState".
Am I passing the wrong thing here? 

`this.appleAuthManager.GetCredentialState( userId , .....`

whereas userId is the credential.user I saved into PlayerPrefs, from the initial login, which also gives me other stuff like name and tokens and stuff. Am I passing the wrong one. Do I instead need to pass appleIdCredential.


here is my Postprocessing : [https://hastebin.com/legoboribe.cs](url)


I'm gonna go over my scripts and try to find the bug again, I hope this time my eyes will catch it.
Thanks for your help really appreciate it.
If I fail again I will probably just remove it altogether, I already had a bad time with the official Unity solution for this and that one didn't have any docs or whatever and was really confusing...

**Comment by devingDev** [comment]
Oh god .... I just saw a severe mistake.
this.appleAuthManager.GetCredentialState( PlayerPrefs.GetString(AppleUserKey),

That actually does not get the user id from the player prefs... that key was for the username >.<'

I'm gonna put the right one in (compile for an hour ...) and then probably close this issue.


It was nice to work with you. I wish you good luck!

**Comment by devingDev** [comment]
Alright seems that fixed it. Logging in works. closing and reopening app takes me straight to the game scene. Revoking Apple sign in from settings shows the sign in again.

Thanks for this beautiful asset!
Good day!

**Comment by lupidan** [comment]
There you go! 😄 
Glad to hear you figured it out.
Also, thanks a lot 😉

**Comment by lupidan** [comment]
Also noticed the typo in the Changelog. It should be June, not May. Ill update that. Thanks!

**Comment by UmarBhatPlaystrom** [comment]
HELL!!! I just experienced the same problem, but I thought that I am not as inattentive as you were (sry for that), so I thought that this is not the case, however I checked it out and here what I saw:
<img width="702" alt="image" src="https://github.com/lupidan/apple-signin-unity/assets/118733948/add65b4a-f373-46d0-aee4-1504ededef59">
