### ISSUE TITLE
Authentication Framework Adds as required not optional 

### ISSUE THREAD

**Issue by osamaraza24** [lupidan/apple-signin-unity#41]
Project.AddCapability(TargetGUID, PBXCapabilityType.SignInWithApple, EntitlementFilename);
            var ProjectCapabilityManager = new ProjectCapabilityManager(ProjectPath,EntitlementFilename, null, TargetGUID);
            ProjectCapabilityManager.AddSignInWithApple();
            ProjectCapabilityManager.WriteToFile();
            
            Project.AddFrameworkToProject(TargetGUID, AuthenticationServicesFramework, true);//true means weak/optional but this adds as required ,which will crash on less than 13 IOS version devices 
            File.WriteAllText(PlistPath, PlistDocument.WriteToString());
            Project.WriteToFile(ProjectPath);

**Comment by osamaraza24** [comment]
what should do for make it optional @lupidan

**Comment by lupidan** [comment]
Hi

There is a well written documentation on how to use a provided extension method to add the capability programatically. Please read it carefully.

https://github.com/lupidan/apple-signin-unity#programmatic-setup-with-a-script

**Comment by osamaraza24** [comment]
Yes ,when I used

**Comment by osamaraza24** [comment]
I used

      var project = new PBXProject();
            project.ReadFromString(System.IO.File.ReadAllText(projectPath));
            var manager = new ProjectCapabilityManager(projectPath,
"Entitlements.entitlements", null, project.GetUnityMainTargetGuid());
            manager.AddSignInWithAppleWithCompatibility(project.GetUnityFrameworkTargetGuid());
            manager.WriteToFile();

with changed "Entitlement.entitlement" to my entitlement name
"Unity.entitlement" it doesn't create entitlement file in my exported
folder, what should I do?

**Comment by lupidan** [comment]
I don't know your post-processing setup...

This Postprocessing extension has been successfully tested with these Unity versions:
✅ Unity 2018.3.14f1
✅ Unity 2018.4.22f1
✅ Unity 2019.3.9f1
✅ Unity 2019.4.0f1 

Seems to me that you might have other Postprocessing builds conflicting with the one you have for this feature. Check if there is more than one entitlements file in your Xcode project. Other than that, whatever issue you are having, seems to be out of the scope of this feature, and a more generic issue.

I would suggest to ask for help in the official Unity iOS forum.
https://forum.unity.com/forums/ios-and-tvos.27/
