### ISSUE TITLE
AddSignInWithAppleWithCompatibility missing

### ISSUE THREAD

**Issue by Nyankoo** [lupidan/apple-signin-unity#42]
I just downloaded the latest version and integrated it in our project for the first time. Following the docs, it seems that `AddSignInWithAppleWithCompatibility` is missing. Checking the metadata of `ProjectCapabilityManager`, it only has `AddSignInWithApple`.
This is in Unity 2019.3.15f

```
var project = new PBXProject();
project.ReadFromString(System.IO.File.ReadAllText(projectPath));
var manager = new ProjectCapabilityManager(projectPath, "Entitlements.entitlements", null, project.GetUnityMainTargetGuid());
manager.AddSignInWithAppleWithCompatibility(project.GetUnityFrameworkTargetGuid());
manager.WriteToFile();
```

**Comment by lupidan** [comment]
I double checked the `.unitypackage` in the releases, and the code is there.
https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/Editor/ProjectCapabilityManagerExtension.cs

As indicated in the documentation, the extension method is located in this namespace.

`using AppleAuth.Editor;`

With that line the extension method should be visible when iOS or tvOS is the selected platform.

**Comment by InternetSalmon** [comment]
@Nyankoo this might be due to building against a different platform (e.g. Android) while `AddSignInWithAppleWithCompatibility ` extension has a` #if UNITY_IOS` compiler directive. I'm not sure what the best approach is, I ended up wrapping my post process script with a iOS compiler directive as well to stop compile errors on different platforms.

**Comment by lupidan** [comment]
@InternetSalmon 
The method is an extension method on `ProjectCapabilityManager`
If the Unity installation does not have the iOS extensions installed, the code shows compile errors.

The `UNITY_IOS` Compile directive is required

Early issue about it:
https://github.com/lupidan/apple-signin-unity/issues/6
