### ISSUE TITLE
Please help describe the flow for when the player taps 'Cancel' on the Apple UI

### ISSUE THREAD

**Issue by michaelcvoigttaco** [lupidan/apple-signin-unity#47]
Is there a callback for this?

**Comment by lupidan** [comment]
You get a Cancelled error
https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/Extensions/AppleErrorExtensions.cs
https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/Enums/AuthorizationErrorCode.cs
