### ISSUE TITLE
can i rotate popup?

### ISSUE THREAD

**Issue by Leuconoe** [lupidan/apple-signin-unity#5]
![주석 2019-10-01 161546](https://user-images.githubusercontent.com/6531761/65941767-c8501780-e466-11e9-9ed0-8e219f810f90.jpg)

orientation of my project is landscape.
Can I rotate popup the same as the project setting?

**Comment by daniel-ys** [comment]
Good point, didn't test this particular scenario. The controller expects a `ASPresentationAnchor`, which is an alias for `UIWindow`
Currently, it's taking the application's main UIWindow as the presenting anchor:
https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/IOS/ObjC/AppleAuthManager.m#L201

I am testing the official example from Apple, and it does not support the rotation there either.
So it seems that, in the current status of the SDK, **Apple does not support rotated popups**.
![Rotation](https://user-images.githubusercontent.com/25744727/65943405-0f72e400-e438-11e9-821c-79e5d99cc85f.gif)

**Comment by lupidan** [comment]
https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/IOS/ObjC/AppleAuthManager.m#L201

The authorization controller requires an `ASPresentationAnchor` to decide from where to show up.


`ASPresentationAnchor` is a type alias for `UIWindow`, so only a UIWindow can be provided to the authorization controller.
We are using the main app's UIWindow.

I have checked the official Apple's example, and it seems that the popup can't be rotated there.


![Rotation](https://user-images.githubusercontent.com/1314521/65950406-a777ca00-e446-11e9-9c15-627dae11097e.gif)


I don't think Apple supports a rotated popup for landscape.
