### ISSUE TITLE
Full name doesn't represent the actual name

### ISSUE THREAD

**Issue by novavision** [lupidan/apple-signin-unity#52]
Unity 2019.3.15, latest plugin version 1.3.0

On first login attempt full name property is incorrect, seems it's not parsed properly. Here what I get in log:
```fullname: AppleAuth.Native.FullPersonName```

 Using another plugin for test I get a proper name

**Comment by lupidan** [comment]
Hi.

Fullname is an IPersonName, not a string, it contains more information to present names, and mimics the Apple's [NSPersonNameComponents](https://developer.apple.com/documentation/foundation/nspersonnamecomponents) class

If you want the full name as a string, use the method `ToLocalizedString()` providing the `PersonNameFormatterStyle` you want. Please check the [example](https://github.com/lupidan/apple-signin-unity/blob/8656e7154385a4f666e638c61fa194670ab82307/AppleAuthSampleProject/Assets/AppleAuthSample/GameMenuHandler.cs#L67..L88) in the sample project:
