### ISSUE TITLE
Sign In failure

### ISSUE THREAD

**Issue by bakalarczuk** [lupidan/apple-signin-unity#54]
Got error on authorization.
Authorization failed: Error Domain=AKAuthenticationError Code=-7071 "(null)"
Sign in with Apple failed Unknown AppleAuth.Native.AppleError
<>c:<SignInWithApple>b__11_1(IAppleError)

I've got Sing in with Apple in entitlements and added in capabilities also

**Comment by lupidan** [comment]
Is this a QuickLogin call?
https://github.com/lupidan/apple-signin-unity#quick-login

**Comment by bakalarczuk** [comment]
Yes

**Comment by lupidan** [comment]
**Please**, read the docs for `QuickLogin`:
[https://github.com/lupidan/apple-signin-unity#quick-login](https://github.com/lupidan/apple-signin-unity#quick-login)

> This should be the first thing to try when the user first runs the application.
>
> If the user has previously authorized the app to login with Apple, this will open a native dialog to re-confirm the login, and obtain an Apple User ID.
>
> If the credentials were never given, or they were revoked, the Quick login will fail.

**The failure is expected.** It helps you detect that the user never used Sign In With Apple before with your app, or that the credentials were revoked, on new installs.

Not an issue.

You can find also a full diagram on how to implement the feature:
[https://github.com/lupidan/apple-signin-unity#implement-sign-in-with-apple](https://github.com/lupidan/apple-signin-unity#implement-sign-in-with-apple)

And there is also a whole example you can check too in the AppleAuthSample directory:
[https://github.com/lupidan/apple-signin-unity/tree/master/AppleAuthSampleProject](https://github.com/lupidan/apple-signin-unity/tree/master/AppleAuthSampleProject)

Closing this.

**Comment by bakalarczuk** [comment]
Hello Daniel.
I have got a major problem. This code

this._appleAuthManager.LoginWithAppleId(
            loginArgs,
            credential =>
            {
                // Obtained credential, cast it to IAppleIDCredential
                var appleIdCredential = credential as IAppleIDCredential;
                if (appleIdCredential != null)
                {
                    // Apple User ID
                    // You should save the user ID somewhere in the device
                    var userId = appleIdCredential.User;
                    PlayerPrefs.SetString(AppleUserIdKey, userId);
                    PlayerPrefs.Save();
                    // Email (Received ONLY in the first login)
                    var email = appleIdCredential.Email;

                    // Full name (Received ONLY in the first login)
                    var fullName = appleIdCredential.FullName;

                    // Identity token
                    var identityToken = Encoding.UTF8.GetString(
                        appleIdCredential.IdentityToken,
                        0,
                        appleIdCredential.IdentityToken.Length);

                    // Authorization code
                    var authorizationCode = Encoding.UTF8.GetString(
                        appleIdCredential.AuthorizationCode,
                        0,
                        appleIdCredential.AuthorizationCode.Length);
                    Debug.Log("APPLE: " + email + ", " + fullName.GivenName + ", " + identityToken + ", " + authorizationCode);
                    // And now you have all the information to create/login a user in your system
                    App.Instance.LogIn(LoginOptions.UNKNOWN);
                }
                // loginPage.SwitchPage("OptionChoosePage");
            },
            error =>
            {
                var authorizationErrorCode = error.GetAuthorizationErrorCode();
                Debug.LogWarning("Sign in with Apple failed " + authorizationErrorCode.ToString() + " " + error.ToString());
            });

is giving me this error:

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object.
  at AppleLogin+<>c.<SignInWithApple>b__9_0 (AppleAuth.Interfaces.ICredential credential) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at AppleAuth.AppleAuthManager+CallbackHandler.ExecutePendingCallbacks () [0x00000] in <00000000000000000000000000000000>:0 


I need to quick implement it to my company app, because of lack in App Store

Can you help me, or give me a point?

Regards,
Marek

**Comment by lupidan** [comment]
Looks like a problem with _your code._
Probably `fullName` is null. And you are trying to print `fullName.GivenName`. Which leads to a NullReferenceException

As it's mentioned in the code:
```
// Full name (Received ONLY in the first login) <=========
var fullName = appleIdCredential.FullName;
```

**Comment by bakalarczuk** [comment]
Yes. I’m little tired of pace, so I didn’t understand properly.
Everything is fine, when I “logout” from Apple sing in.
After that I receive proper data

Thank you.

Regards
Marek
