### ISSUE TITLE
AppleAuthManager.IsCurrentPlatformSupported & iOS 12

### ISSUE THREAD

**Issue by criistii-toptal** [lupidan/apple-signin-unity#56]
It seems "AppleAuthManager.IsCurrentPlatformSupported" is returning true for iOS 12. I feel it should be false, or am I missing something?

Thanks,

**Comment by lupidan** [comment]
Hi, I double checked the code. The native method only returns true in one specific place, and it's surrounded by an availability check for iOS 13.

https://github.com/lupidan/apple-signin-unity/blob/8656e7154385a4f666e638c61fa194670ab82307/AppleAuth/Native/iOS/AppleAuthManager.m#L346

Are you sure you aren't running on iOS 13?

**Comment by criistii-toptal** [comment]
Hey. Not sure what happened but you are correct, it is working. I probably messed something up in the code.
