### ISSUE TITLE
Xcode Build Failed  - Library not found for -IFirebaseAuth

### ISSUE THREAD

**Issue by Antonio78318** [lupidan/apple-signin-unity#57]
Hi! I tried to make an AppleSignin on my unity game, and the user can get authentication into firebase, so I follow your tutorial step by step, I got an error when I built in Xcode, It shows Library not found for -IFirebaseAuth, But I already import firebaseauth package into my unity project, Do I miss something? Please help me with that, Thank you in advance :)
![Error](https://user-images.githubusercontent.com/33215857/89491825-b5bf1100-d7e2-11ea-9dfd-6429fa549e53.jpg)

**Comment by lupidan** [comment]
Hi

It seems there is some misconfiguration on your build, not finding the `FirebaseAuth` library, therefore, this is related to Firebase integration with Unity.

Please go to the official support page for Firebase.
[https://firebase.google.com/support](https://firebase.google.com/support)
