### ISSUE TITLE
FirebaseException - The nonce in ID Token does not match

### ISSUE THREAD

**Issue by carlplaylab** [lupidan/apple-signin-unity#58]
**Error** 
Firebase.FirebaseException: The nonce in ID TOKEN "noncestring" does not match the SHA256 hash of the raw nonce "noncestring" in the request.

I have tried using the same nonce string for Apple login and Firebase oath and also tried SHA256 for Apple login where the error becomes: 

Firebase.FirebaseException: The nonce in ID TOKEN "sha256 of noncestring" does not match the SHA256 hash of the raw nonce "noncestring" in the request.

Must AppleAuthManager  receive a different form of nonce string?

**Comment by carlplaylab** [comment]
Closing this as my SHA256 method was wrong. Correct method is the one here: https://github.com/lupidan/apple-signin-unity/blob/master/docs/Firebase_NOTES.md using SHA256Managed

**Comment by lupidan** [comment]
There is official documentation on how to do it natively on iOS:
https://firebase.google.com/docs/auth/ios/apple#sign_in_with_apple_and_authenticate_with_firebase

There is also a *tentative* guide on how to do it with this plugin:
https://github.com/lupidan/apple-signin-unity/wiki/Sign-in-with-Apple-Unity-Plugin:-Working-with-Firebase

You give the RAW Nonce (a.k.a the one you must create) to Firebase
You give the SHA256 of that RAW NONCE to Apple
