### ISSUE TITLE
Update user identifier after game transfered state

### ISSUE THREAD

**Issue by Leinnan** [lupidan/apple-signin-unity#59]
Based on this article: https://medium.com/swlh/get-the-most-out-of-sign-in-with-apple-e7e2ae072882
When we transfer ownership from one team to another we should update user identifier. For now we can't or there is some way that I am not aware of?

**Comment by lupidan** [comment]
There is a equivalent credential state when a user is transferred:
[https://github.com/lupidan/apple-signin-unity/blob/8656e7154385a4f666e638c61fa194670ab82307/AppleAuth/Enums/CredentialState.cs#L26](https://github.com/lupidan/apple-signin-unity/blob/8656e7154385a4f666e638c61fa194670ab82307/AppleAuth/Enums/CredentialState.cs#L26)

According to that website:
> Silent migration This migration is handled silently. This is without any user interaction and can be triggered calling the same API used to create a new account or logging the user.

I haven't been able to test this scenario, but looking at the native code, my guess is this one:

1. The user did already sign in with apple in the app. You should have stored the User ID in the device, and you must be calling `GetCredentialState` everytime you open the app.
2. If you get `CredentialState.Transferred` it means the app was transferred, therefore you need to get a *NEW user ID* for the new app ownership. If that's the case, according to the docs, you should make a call to `QuickLogin`.
3. That `QuickLogin` call should succeed with the *NEW user ID*, you should then update the user's information in your backend, and save the new user ID for future calls to `GetCredentialState`.
4. From now on, `GetCredentialState` should succeed with the new user id that you obtained.

Does this answer the question?

**Comment by Leinnan** [comment]
For now its all I need to know. Thanks!
