### ISSUE TITLE
exception handling for editors without IOS modules installed.

### ISSUE THREAD

**Issue by Leuconoe** [lupidan/apple-signin-unity#6]
![주석 2019-10-02 123153](https://user-images.githubusercontent.com/6531761/66016247-d22e5500-e510-11e9-87b1-f31d145615ee.jpg)
Requires the use of scripting define symbols.

![주석 2019-10-02 123535](https://user-images.githubusercontent.com/6531761/66016347-37824600-e511-11e9-89fb-09458b1c13b5.jpg)

**Comment by Leuconoe** [comment]
SignInWithApplePostprocessor.cs,  ProjectCapabilityManagerExtension.cs

**Comment by lupidan** [comment]
Thanks for the report. It should be now fixed in master.
