### ISSUE TITLE
Is it possible to not get the user's email or full name?

### ISSUE THREAD

**Issue by Kezzo** [lupidan/apple-signin-unity#60]
For GDPR and general privacy reasons I would like to set the login scope to not include the user's email or full name.
The `LoginOptions` enum only allows setting either of them or both, but doesn't included a value to exclude both scopes.
Is this because of how Apple SignIn works or would it be possible to get this implemented into this plugin?

**Comment by lupidan** [comment]
You are right, there is no specific value for No scopes.
But since `LoginOptions` is a `Flags` enum, just passing `0` should work and not request any scope.

I hope that helps.

**Comment by Kezzo** [comment]
Thanks a lot for this! I tested it and it works well!

I also submitted a pull request to add this information to the FAQ:
https://github.com/lupidan/apple-signin-unity/pull/65/commits

**Comment by lupidan** [comment]
Thanks for the PR! Merged!
