### ISSUE TITLE
Apps using Apple Id Icon

### ISSUE THREAD

**Issue by sais15** [lupidan/apple-signin-unity#61]
Hello,

Maybe this is not the correct forum to ask this question. But I do not get my app icon in apple setting view-> in the menu-> Apps using Apple Id. All other icons are visible( including under normal settings) and are set up through unity.  Do you have any idea about this?  I'm still testing my application only through Test Flight, could this be the reason.

**Comment by lupidan** [comment]
The settings menu for the "Apps using Apple Id" is managed by iOS and Apple.
There is no extra configuration for that menu besides, I assume, the App icons you have to set in Unity.

Closing this
