### ISSUE TITLE
Filename: currently not available on il2cpp Line: -1

### ISSUE THREAD

**Issue by menesbeser** [lupidan/apple-signin-unity#62]
Filename: currently not available on il2cpp Line: -1
I get this error

**Comment by lupidan** [comment]
Hi

The line you copy pasted is too generic to even know if it is related to this plugin.
Normally that line is preceded with a stack trace, which can give you a clue on where the exception/error is happening.

**Comment by menesbeser** [comment]
run my device and if I click sign in with apple I get only (Filename: currently not available on il2cpp Line: -1) error

**Comment by lupidan** [comment]
Please provide a sample project that reproduces the error.
