### ISSUE TITLE
Relogin works in 1.0.0, but doesn't work in 1.2.0 and 1.3.0

### ISSUE THREAD

**Issue by VladimirBelchenkoKG** [lupidan/apple-signin-unity#63]
Reloginning doesn't return credentials in version 1.2.0. Is this intended behaviour? I read the answer in README, telling that Apple gives credentials (email and stuff) only once. But the ability to repeatedly get credentials in 1.0.0 really confused me.

**Comment by lupidan** [comment]
> Reloginning doesn't return credentials in version 1.2.0. Is this intended behaviour?

You will get email and name *only once*, it's your responsability to save them somewhere in your backend.
If you want to get the name and email again, you need to [revoke credentials first](https://github.com/lupidan/apple-signin-unity#how-can-i-logout-does-the-plugin-provide-any-logout-option).

Finally, you should get the Apple User ID and other elements always (like IdentityToken or AuthorizationCode), as long as the Login/Quick login call succeeds of course.

> But the ability to repeatedly get credentials in 1.0.0 really confused me.

This was never the case before, it just wasn't properly documented or discovered. The initial Apple documentation for this feature was quite lacking at first.

Hope the answer clears it up. Closing this.

**Comment by VladimirBelchenkoKG** [comment]
Thank you for the answer!
