### ISSUE TITLE
Error 1001 - Canceled

### ISSUE THREAD

**Issue by fabio-chimera** [lupidan/apple-signin-unity#66]
I'm having this error when I try to login:

Canceled - The operation couldn't be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.) 

Am I doing something wrong in the Xcode or Itunes Connect?

Ps: The game is not published yet.

**Comment by lupidan** [comment]
Yes...
You are cancelling the popup, that's why the error is "Canceled"

Closing this
