### ISSUE TITLE
I can't login, Sign Up Not Completed

### ISSUE THREAD

**Issue by bluekid** [lupidan/apple-signin-unity#67]
Hello, thanks your support plugin.

I can't sign in with apple.
here is my work process, what's wrong?

1. create empty project in unity 2019 4.9f1
2. import asset by asset store
3. build xcode project : bundle id is same my game.
4. xcode play button click, compile and run
5. I can't sign in : Sign Up Not Completed

please help, Why I can't sign in...
![Photo_2020-09-16-11-27-39](https://user-images.githubusercontent.com/4442927/93285621-48a29080-f810-11ea-865d-ad8f843cae29.jpeg)

**Comment by lupidan** [comment]
Whatever is happening inside the native dialog to Sign in is something related to Apple.

I suggest googling the error and looking at the official forums. There seems to be some discussion in this thread:
https://developer.apple.com/forums/thread/122458

**Comment by bluekid** [comment]
> Whatever is happening inside the native dialog to Sign in is something related to Apple.
> 
> I suggest googling the error and looking at the official forums. There seems to be some discussion in this thread:
> https://developer.apple.com/forums/thread/122458

thanks your answer lupida.
that discussion about using REST API...
i can't find solution yet.

**Comment by lupidan** [comment]
They also mention some app cases as well, if you keep reading.

> I have found a solution, it works for me, I hope it can help you.
Here is my solution:
1 Enter the edit page of my App ID on Apple developer website.
2 Uncheck the "Sign In with Apple" option in the capabilities list, then click save.
3 Check the "Sign In with Apple" option again, and click save.

Like here:
[https://developer.apple.com/forums/thread/131212](https://developer.apple.com/forums/thread/131212)
> After re-checking the 'Sign in with Apple' option on the account, we can login successfully

Have you tried doing that on Apple's website (uncheck save, recheck save)?

If it keeps happening, I would extremely suggest opening a bug ticket for Apple. Whatever happens inside that native dialog is all them.

**Comment by evst-dev** [comment]
I am having the same problem.
Apple login works with one of the two accounts (one for the team management role and the other for the owner), but the team management account has the same problem as above. Even if you recreate the authentication and apply the ID at build time, the above message appears and does not work for Apple login to the team management account.

**Comment by bluekid** [comment]
> I am having the same problem.
> Apple login works with one of the two accounts (one for the team management role and the other for the owner), but the team management account has the same problem as above. Even if you recreate the authentication and apply the ID at build time, the above message appears and does not work for Apple login to the team management account.

I have a question.
Is "team management account" an Apple Developer's team-managed account?

**Comment by evst-dev** [comment]
> > I am having the same problem.
> > Apple login works with one of the two accounts (one for the team management role and the other for the owner), but the team management account has the same problem as above. Even if you recreate the authentication and apply the ID at build time, the above message appears and does not work for Apple login to the team management account.
> 
> I have a question.
> Is "team management account" an Apple Developer's managed account?
> My apple id is an Apple Developer's managed role.

Yes, It has managed role.
all permission were granted without owner role.
