### ISSUE TITLE
No callback from QuickLogin if user cancels.

### ISSUE THREAD

**Issue by PaulNaylor** [lupidan/apple-signin-unity#68]
Hi lupidan,
Firstly, thanks for the great plugin. We needed SignInWithApple urgently and this plugin is really helping.
In testing though I've found that when I click 'continue' then 'cancel' on the Quick login screen - I get neither the success nor error callback called.
I can see the following in the logs:
```
AuthKit           Authorization failed: Error Domain=AKAuthenticationError Code=-7003 ...
AuthKitUIService  AKRemoteViewController did complete with authorization (null) (error ... -7003)
```
... but looking at the code either the success or error callbacks should be called, yet neither is. Do you have any thoughts on this? 

my code follows below (sorry if it's a bit messy, it's work in progress):
```
	public static void AttemptQuickLogin()
	{
		var quickLoginArgs = new AppleAuthQuickLoginArgs();

		_appleAuthManager.QuickLogin(
			quickLoginArgs,
			credential =>
			{
				// Received a valid credential!
				// Try casting to IAppleIDCredential or IPasswordCredential

				// Previous Apple sign in credential
				var appleIdCredential = credential as IAppleIDCredential;
				if (appleIdCredential != null)
				{
					_isSignedInWithApple = true;
					_appleUserId = credential.User;
					PlayerPrefs.SetString(AppleUserIdKey, _appleUserId);
					_pleaseUpdateServer = true;
				}

				// Saved Keychain credential (read about Keychain Items)
				var passwordCredential = credential as IPasswordCredential;
				// ?
				Debug.Log("SignInWithAppleClass: _initComplete = true");
				_initComplete = true;
			},
			error =>
			{
				//var authorizationErrorCode = error.GetAuthorizationErrorCode();
				// Quick login failed. Show login button on settings.
				_isSignedInWithApple = false;
				Debug.Log("SignInWithAppleClass: _initComplete = true");
				_initComplete = true;
			});
	}

```

**Comment by PaulNaylor** [comment]
Ah... is it because the callback is on another thread?... you warned about that I think. So I won't see those debug logs?

**Comment by lupidan** [comment]
Are you calling `Update` on the auth manager?

https://github.com/lupidan/apple-signin-unity#initializing

**Comment by PaulNaylor** [comment]
> Are you calling `Update` on the auth manager?
I thought I was, but turns out a mistake on my part meant that it was not getting called as expected.
Thank you so much for pinpointing that so quickly!
