### ISSUE TITLE
Unable to view Username and email 

### ISSUE THREAD

**Issue by Siddhant-pixel** [lupidan/apple-signin-unity#71]
@lupidan  Hello. I used your plugin, but I am not able to retreive username and email. It is showing empty input fields, One at one time it showed me the Username and email. I have logout the account from my iPad as well and login again and repeated the same procedure as you have told to do.But still no luck.It showing empty fields. Any guess what to do ?

**Comment by lupidan** [comment]
You only receive email and name the first time the user signs in with your app.
You won't receive email or name after the first time, unless you Revoke the credentials
Login out of the iPad is not revoking credentials, you have to go to a specific settings menu.

It's all explained in the FAQ

https://github.com/lupidan/apple-signin-unity#i-am-not-getting-a-full-name-or-an-email-even-though-i-am-requesting-them-in-the-loginwithappleid-call

**Comment by Siddhant-pixel** [comment]
Hello. Understood but is there any alternative that i could logout that
thing from within the app instead of going to settings

**Comment by lupidan** [comment]
No. It's in the FAQ as I mentioned.

https://github.com/lupidan/apple-signin-unity#how-can-i-logout-does-the-plugin-provide-any-logout-option

**Comment by Siddhant-pixel** [comment]
Okay thanks

**Comment by Siddhant-pixel** [comment]
Hello i have a small question. i need to check at the very start when we
open the app >>> to check whether we are login via apple or not. How to
achieve this thing?

**Comment by lupidan** [comment]
I don't understand exactly what your question is, but there is some detailed information in the Readme, and even a flow diagram on how it works:
https://github.com/lupidan/apple-signin-unity#implement-sign-in-with-apple

**Comment by Siddhant-pixel** [comment]
Actually , when we open the app. I need to check whether we are loged in
via apple or not . Is there any method to check this thing.Did you
understood my point?

**Comment by lupidan** [comment]
**Please** read the documentation:
https://github.com/lupidan/apple-signin-unity#checking-credential-status

**Comment by Siddhant-pixel** [comment]
Hello i have read the doc. I have understood it .I have shared the script
please have a look and guide me . I need to check that is user is already
logged in the app or not . So i am checking the credentials state but not
getting any trace

**Comment by Siddhant-pixel** [comment]
Hello do you have any suggestionS?
