### ISSUE TITLE
CFBundleIdentifier Collision

### ISSUE THREAD

**Issue by sergiosolorzano** [lupidan/apple-signin-unity#72]
Hi there

On MacOSX build after codesigning and I try to upload with Transporter I can't upload it getting Transporter Delivery error

ERROR ITMS-90511 @CFBundleIdentifier Collision. The info.plist CFBundleIdentifier value 'com.lupidan.MacOSAppleAuthManager" of 'appname.app/Contents/Plugins/MacOSAppleAuthManager.bundle' is already in use by another application"

Any ideas how to work around this please?

I had codesigned MacOSAppleAuthManager
codesign -vvv --force --timestamp --options runtime -s "3rd Party Mac Developer Application: Name (code)" "appname.app/Contents/Plugins/MacOSAppleAuthManager.bundle"

Do I need to add any reference to MacOSAppleAuthManager in Info.plist?

Thanks a bunch for your help

**Comment by lupidan** [comment]
Hello, and first of all. **Thanks a lot for taking the time to report this bug**

This is an interesting bug you found. The provided `MacOSAppleAuthManager.bundle` has, by default, that Bundle Identifier (`com.lupidan.MacOSAppleAuthManager`) that I set when creating the plugin, and I guess that someone has taken over and claimed their own... 😅

I believe to quickly fix this, you need to change that identifier to something of your own.

Basically, open the Info.plist **inside the MacOSAppleAuthManager.bundle**:
`appname.app/Contents/Plugins/MacOSAppleAuthManager.bundle/Contents/Info.plist`

Locate these lines:

```
    <key>CFBundleIdentifier</key>
	<string>com.lupidan.MacOSAppleAuthManager</string>
```

and change it to something of your own, like:
```
    <key>CFBundleIdentifier</key>
	<string>com.yourapp.MacOSAppleAuthManager</string>
```

Then codesign with the developer certificate again, check that it still works.
Finally try uploading the App with Transporter, and let me know if it fixes the issue.

I need to figure out a way to automate this in post processing, or at least not have this issue when uploading the app to the App Store.

**Comment by lupidan** [comment]
So I was able to get a repro of this particular bug.
Getting the `.pkg` to get verified will return an issue with the Bundle identifier as you mentioned.

I tried to replace that conflicting bundle identifier to a custom one, and even better, to the same bundle identifier as the main `.app` file. I then codesigned the app again, and made the `.pkg` file.

In both tries, after verifying it, the issue was gone.

I'll still leave this open, since I think the plugin should have some postprocessing script to change the bundle identifier of the `MacOSAppleAuthManager.bundle` inside the built `.app`

**Thanks a lot for reporting this bug**

**Comment by sergiosolorzano** [comment]
Hey @lupidan 

Not at all, thank you for making the effort to put together this great asset !!

And ofc thanks a bunch for your prompt response. I actually did some further research on the web after posting and found suggestions (similar problem people had with cocoapods) to add .macOS at the end like:
<key>CFBundleIdentifier</key>
	<string>com.lupidan.MacOSAppleAuthManager.macOS</string>

and worked and uploaded great. I'm now awaiting apple's approval and will update this post accordingly👍 

I didn't get an error with your suggestion either so i'd guess apple's review would also worke out if mine does

Thanks a bunch for your help  and this amazing asset !

**Comment by sergiosolorzano** [comment]
Hey @lupidan 
I had confirmation today by Apple the build was accepted having used ".macOS" at the end :)

Thanks again for your help ! Cheers, Sergio

**Comment by lupidan** [comment]
Version 1.4.0 was released today. It contains a Post processor helper method to avoid encountering this issue when uploading to the MacOS App Store.

More info can be found here:
https://github.com/lupidan/apple-signin-unity/tree/v1.4.0#plugin-setup-macos

Closing this.

**Comment by ShivamGarg91** [comment]
Hi
On my ios device, i'm getting "sign up not completed" message when i tried to sign in.

**Comment by Pramod-Redapple** [comment]
Hi , i am getting full name and email id as null every time.

**Comment by ShivamGarg91** [comment]
Hi,
Re-invoke signin account from settings in your apple device and try again.
