### ISSUE TITLE
Full name,Email

### ISSUE THREAD

**Issue by SnnYsf** [lupidan/apple-signin-unity#77]
unity 2017,
ios 13 x
mail and name are definitely not coming

**Comment by lupidan** [comment]
https://github.com/lupidan/apple-signin-unity#i-am-not-getting-a-full-name-or-an-email-even-though-i-am-requesting-them-in-the-loginwithappleid-call

**Comment by lupidan** [comment]
Also, clearly stated in the sample:
https://github.com/lupidan/apple-signin-unity#perform-sign-in-with-apple

```
// Email (Received ONLY in the first login)
var email = appleIdCredential.Email;

// Full name (Received ONLY in the first login)
var fullName = appleIdCredential.FullName
```

If this is not your case. Please provide a sample project that reproduces the issue.
