### ISSUE TITLE
How to get expiry of the authToken and a "refresh token"?

### ISSUE THREAD

**Issue by derwaldgeist** [lupidan/apple-signin-unity#80]
First of all, thanks a lot for this package, works like a charm!

I am trying to integrate the apple sign in with a Meteor-based backend, which already has an OAuth-based flow of Sign in with Apple in place. After analyzing its code, I realized that the Meteor flow expects:

1. The expiry date (timestamp) of the authToken (aka Authorization Code), and
2. A refresh token, in case the authToken is expired

Both of these are handed over from Apple during OAuth. Is there a chance to these values via the native API as well? I could not find them in the existing C# API.

**Comment by lupidan** [comment]
Found some answer here:
https://developer.apple.com/forums/thread/117867

So in the **first login** of the user, you should be getting an Authorization Code to use with a backend endpoint and get a refresh token. The authorization code is inside the IAppleIDCredential
https://github.com/lupidan/apple-signin-unity#perform-sign-in-with-apple

After that, the client just needs to store the apple user ID in the device, and use it with the `GetCredentialState` call to know if it's still authorized.
https://github.com/lupidan/apple-signin-unity#checking-credential-status

Hope that helps

**Comment by derwaldgeist** [comment]
Thanks @lupidan. I have seen that the client can (and should) regularly check the status. However, on the server side, it is not that easy to perform these checks.

In my app, I have two ways of authenticating: The rich client (Unity) and a web frontend (based on React). The latter uses Meteor as its backend, and the Apple OAuth implemented there gets you an explicit "refresh token" to refresh the credentials. So I was wondering if that was something that was missing in your API?

**Comment by lupidan** [comment]
This plugin is a wrapper for what Apple offers in their AuthorizationServices SDK. And the SDK, as far as I know, does not offer a way to get a refresh token.

Again, how they seem to suggest it should be done is like this:

**Client)** First login gets you the Apple User ID and an Authorization Code to send to your backend. Checking the validity of a user, from now on, should be done with `GetCredentialState` and that Apple User ID.

**Server)** Receives data from the first login to create the user. Uses that received Authorization Code to get a refresh token for the user. Refreshes the token once a day.
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user

**Comment by derwaldgeist** [comment]
Ok, thanks, that was the confirmation I needed.
