### ISSUE TITLE
How can I pass redirect_uri when I call _appleAuthManager.LoginWithAppleId()?

### ISSUE THREAD

**Issue by neoxu** [lupidan/apple-signin-unity#81]
I would like to sync user's id_token to my server. How can I request https://appleid.apple.com/auth/authorize and pass the client_id, redirect_uri and response_type when I call _appleAuthManager.LoginWithAppleId() in Unity?

Article of Apple below:
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms

**Comment by lupidan** [comment]
Hi

This plugin is to support the native SDK from Apple... it's not for the Javascript version of the plugin, or the REST API
