### ISSUE TITLE
Email only in first login

### ISSUE THREAD

**Issue by jay-neb** [lupidan/apple-signin-unity#82]
Hi there,

We are having an issue getting our app approved by Apple. We have implemented your plugin and it provides the user's email only on the first login, as shown in the example. We are having some issues with account creation and user permissions because we can only fetch the email the first time but as Apple explains in [this link](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple), we can get the email any time:

_While Apple provides the user’s email address in the identity token on all subsequent API responses, it doesn’t include other information about the user, such as their name. When you receive user information from the API response, immediately store it locally so your app can access it again in the event of a process or network failure._

Is it possible that the plugin has this limitation? If you think it can be fixed by changing some of the native code, I could take a look and submit a pull request when done.

Thanks,

Jay

**Comment by lupidan** [comment]
The plugin is a wrapper around Apple's native API. Apple just decided that, on subsequent calls to Sign In, it won't provide the Email or Name in the [corresponding fields](https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidcredential), however I don't know if the email is contained in the [IdentityToken](https://github.com/lupidan/apple-signin-unity/blob/master/AppleAuth/Interfaces/IAppleIDCredential.cs#L10).

Feel free to investigate and post your findings about it. With that said, even if it's inside the IdentityToken, I don't think the plugin should be parsing that information at all, but it should be handled by the backend, or whatever service you provide the IdentityToken to.

Thanks for commenting with this information.

**Comment by bhupiister** [comment]
Even if the user logs In for the first time, email address is not received. Even when the user gets the consent screen, it only has a checkbox in front of the username, email address consent is not even asked from the user.

**Comment by lupidan** [comment]
@bhupiister  If you get the name, but not the email, in the consent screen, you might be calling `LoginWithAppleId` with the wrong arguments.
https://github.com/lupidan/apple-signin-unity#perform-sign-in-with-apple

Please provide a sample code that reproduces your issue.

**Comment by jay-neb** [comment]
I just realised that I never replied to this with my findings. I managed to get the data from IdentityToken as per your suggestions @lupidan. For anyone interested, the steps to follow are:

- Get `IdentityToken` from the `appleIdCredential` object. It's important to note that the type of `IdentityToken` is `byte[]` and it must be converted to `string`.

- Convert `IdentityToken` to a `string` like this:
```
var identityToken = appleIdCredential.IdentityToken;
var identityTokenStr = Encoding.UTF8.GetString (identityToken, 0, identityToken);
```

- Send `identityTokenStr` to your backend which should decode it and send back the user's email and Apple ID.

- To implement the decoding in your backend, you can follow [this very useful tutorial](https://sarunw.com/posts/sign-in-with-apple-3/).

Note that to implement the decoding in your backend you will need to integrate a JWT/JWK library. In my case, my backend is written in PHP and I am using [this library](https://github.com/firebase/php-jwt), but you'll surely find a similar library for NodeJS, Python, etc.

**Comment by lupidan** [comment]
@jay-neb Thanks a lot for your reply 🙏 
Inputs like the one you posted are **very** appreciated.

**Comment by bhupiister** [comment]
@lupidan  Hey, the problem was with such users who do not have an email address as their apple id but instead have a mobile number. Nothing wrong with your code. Though, can you let me know if we can include a mobile number in the scope if needed?

**Comment by lupidan** [comment]
@bhupiister Nope, only name and email:

https://developer.apple.com/documentation/authenticationservices/asauthorizationscope?language=objc

**Comment by bhupiister** [comment]
> @bhupiister Nope, only name and email:
> 
> https://developer.apple.com/documentation/authenticationservices/asauthorizationscope?language=objc

ok, got it. Thanks for the link and code.
