### ISSUE TITLE
DllNotFoundException - Big Sur

### ISSUE THREAD

**Issue by sergiosolorzano** [lupidan/apple-signin-unity#83]
Hello,
I have upgraded to Big Sur on Macos, trying to run dev build and i'm getting the error below

DllNotFoundException: Unable to load DLL 'MacOSAppleAuthManager': The specified module could not be found. 
>AppleAuth.AppleAuthManager+Pinvoke.AppleAuth_IsCurrentPlatformSupported () (at <000000000000000000000000>:0)
AppleAuth.AppleAuthManager.get_IsCurrentPlatformSupported () (at <000000000000000000000000>:0)

Anyone having probs with Big Sur or plugin maybe been tested? Any other ideas what the issue maybe? all of lupidan files are still in the same place in the project folder where they were before upgrading to Big Sur.

Thank you
Unity 2020.2.0b11.3484
Dev Build Architecture in Build Settings =Intl 64-bit + Apple Silicon

UPDATE: my apologies, I've tried Intl 64-bit only and works :)

**Comment by lupidan** [comment]
It could be that the macOS library does not have ARM support. Unfortunately I don't have a new ARM machine to test it out just yet.

**Comment by sergiosolorzano** [comment]
Do you mean the unitys’ macos library or big surs?

Thank you

**Comment by lupidan** [comment]
I mean the `MacOSAppleAuthManager.bundle` containing the native code for the plugin only supports x86_64. It was not built for Apple Silicon.

```
user@host % lipo -info MacOSAppleAuthManager
Non-fat file: MacOSAppleAuthManager is architecture: x86_64
```

To support silicon, it should also say `arm64` in there. The plugin was build some time ago. We need to make a new version with an updated bundle for MacOS

If you are in a hurry, you can always compile your own `MacOSAppleAuthManager.bundle`, the Xcode project is provided in the repository.

**Comment by sergiosolorzano** [comment]
Ah, got’cha, sorry I didn't understand.

No no, im not publishing for the new silicon so intel only selection in unitys build works. 

I have submitted to apple see what they say.

Thank you!

**Comment by lupidan** [comment]
v1.4.1 was released with experimental Apple Silicon (ARM) support for macOS
Closing this, but anyone feel free to comment if you find issues in any of the new macOS machines.
