### ISSUE TITLE
no plugin on built app for architecture intel64+apple silicon

### ISSUE THREAD

**Issue by sergiosolorzano** [lupidan/apple-signin-unity#91]
Hello @lupidan 

Thanks a bunch for the updated build with apple silicon!

I am sorry I had not come back with the git issue I raised about [dllnotfoundexception](https://github.com/lupidan/apple-signin-unity/issues/83) on big sur. fyi I submitted my app to apple but had the app rejected. I am not clear if it had to do with this the library not having arm support at the time.

I have built a dev app with intel64+apple silicon but the plugin does not show in the package contents. Am I doing something wrong? If I built intel64 only it does.

Thank you for your help!

**Comment by lupidan** [comment]
Are you using v1.4.1 ?
https://github.com/lupidan/apple-signin-unity#installation

**Comment by sergiosolorzano** [comment]
yep, 1.4.1 and beta 2020.2.0b12

**Comment by lupidan** [comment]
Could you provide a 2020.2.0b12 small project that reproduces the issue?
I personally tested it on 2020.2, and I got it working 🤔
It was using the local package though...

**Comment by sergiosolorzano** [comment]
I'll work on that and come back yes

**Comment by lupidan** [comment]
I'll give it a go with a clean project later today as well. 👍

**Comment by sergiosolorzano** [comment]
Great @lupidan   I'll get on with it later tonight or in the morning. One thing I've noticed that may be a separate issue, not sure: when building intel64+apple silicon I get the build completed successful debug msgs but I also get this error

AppleAuthMacosPostprocessorHelper: Error while fixing MacOSAppleAuthManager.bundle bundle identifier :: Could not find a part of the path "/Users/username/Documents/appdir/Build-Dev/appname.app/Contents/Plugins/MacOSAppleAuthManager.bundle/Contents/Info.plist".

it seems that AppleAuthSample.Editor SignInWithApplePostprocessor OnPostProcessBuild executes even though I'm not executing the sample. VS does not show the reference that is calling onto OnPostProcessBuild to execute. This error only happens when architecture is set to intel64+apple. 
If I comment the line below in OnPostProcessBuild the Build competes successfully without this error (but the plugin is still missing)

else if (target == BuildTarget.StandaloneOSX)
            {
                AppleAuthMacosPostprocessorHelper.FixManagerBundleIdentifier(target, path);
            }

**Comment by lupidan** [comment]
Made an empty project on Unity 2020.2.0v11
Added the v1.4.1 plugin through the `packages.json` file, referencing the remote github url.
Made a build for Intel+Apple Silicon, and the `.bundle` is correctly added into the `.app` file 🤷‍♂️ 

![Screenshot 2020-12-01 at 19 22 50](https://user-images.githubusercontent.com/1314521/100774314-9e97d500-340a-11eb-8e0c-0647c35bfb23.png)

I also tried generating an Xcode project, and the `.bundle` is correctly added to the Xcode file

![Screenshot 2020-12-01 at 19 29 30](https://user-images.githubusercontent.com/1314521/100775156-8d9b9380-340b-11eb-9125-ab0d03c3f698.png)

Try cleaning your packages cache, it could be that some local changes on the plugin meta files are overriding the default configuration of those meta files. Make sure the bundle inside the plugin folder is selected for Any CPU.

![Screenshot 2020-12-01 at 19 27 58](https://user-images.githubusercontent.com/1314521/100775225-a86e0800-340b-11eb-9b3d-c8aceea45e51.png)

**Comment by lupidan** [comment]
Postprocessing only works when building an `.app` file. Support for postprocessing for macOS Xcode project generation is not yet supported.
Still, even with the postprocessing fails, the `.bundle` is correctly added.

I really think it might be something related to your package files cache

**Comment by sergiosolorzano** [comment]
Hi @lupidan I have prepared the downsized project but I think I can save you from looking into it because in reading your post I see and confirmed what the problem was, maybe this is my issue only? When I select an architecture on File-Build Settings-Architecture , whatever choice I make does not apply the change in MacOSAppAuth as per your third snapshot. Does changing the architecture in Build settings change it automatically in MacOSAppAuth for you? 
So I had been building with the wrong architecture selected in MacOSAppAuth. Now that I manually make the change it works :)

A question please - when should I select "Editor" as a platform on MacOSAppAuth ?

Thank you for your help!

**Comment by lupidan** [comment]
> Does changing the architecture in Build settings change it automatically in MacOSAppAuth for you?
It doesn't have to change anything. It should stay as "Any CPU" which is the original value.
"Any CPU" involves that it will be included whatever the build architecture is.

**Comment by lupidan** [comment]
> A question please - when should I select "Editor" as a platform on MacOSAppAuth ?

If you mean the `MacOSAppleAuthManager.bundle` file, you shoudn't change anything there.
The plugin code should be read only
It's disabled for the editor for a reason.

**Comment by sergiosolorzano** [comment]
Thanks a lot @lupidan , that's all clear now! Again thank you so much for preparing this cool asset, really enjoying it !!!
