### ISSUE TITLE
Error 1001

### ISSUE THREAD

**Issue by AnkitCIS** [lupidan/apple-signin-unity#92]
We have got an error when we are sign-in with an apple com.apple.authenticationservices.authorizationerror error 1001 . Please solve this issue as soon as possibe

**Comment by lupidan** [comment]
It's a Canceled error. It's how the native code works when the user cancels the sig in attempt. 

https://developer.apple.com/documentation/authenticationservices/asauthorizationerror/code/canceled

And you are being rude.
Closing
