### ISSUE TITLE
Cannot build: What settings please, can't find documentation

### ISSUE THREAD

**Issue by sergiosolorzano** [lupidan/apple-signin-unity#94]
Hello @lupidan and everyone

I hope you're well. I'm reaching out for help please.

I broke the project trying to get the settings right for this plugin - ta-da!! I brought it back to life but I cannot build because this plugin errors show appleauth/editor/appleauthmacospostprocessorhelper - the type or namespace name BuildTarget could not be found are you missing referefence

I am testing these settings because I've had an app rejected again (after Big Sur release and M1 entry), I don't know if it has to do with this plugin so I am checking each plugin in the project and I need to make sure I have the correct settings for your great asset.

Unfortunately I could not find documentation for these settings. Can I please confirm, I am building for macos, what settings should I use for:

- AppleAuth-General, Assembly Definition References should I check off GUIDs? Do I need to choose Editor along macos, or only macos is ok?
- Apple Auth.Editor - Assembly Definition References should I check off GUIDs? Do I need to choose Editor along macos, or only macos is ok?
- MacOS Apple Auth Manager.bundle -> should I Include any other platform than Standalone? Should I check Load on startup?

I find guessing what is the right setting here confusing, maybe it's only me but my guess is someone else may land with the same problems. If someone can help answering it'll be helpful for everyone in the future. I already spent a day trying to figure this out

Thank you for your help

**Comment by lupidan** [comment]
> I broke the project trying to get the settings right for this plugin - ta-da!! I brought it back to life but I cannot build because this plugin errors show appleauth/editor/appleauthmacospostprocessorhelper - the type or namespace name BuildTarget could not be found are you missing referefence

You **DON'T** have to modify the assembly files for the plugin.
The code in the `Editor` folder is Editor only, that's why the `Apple Auth.Editor` namespace has only "Editor" selected. If you mark anything else, the project will fail to compile.

Remove the plugin, refresh the project, and re-add the plugin.
I repeat, you **DON'T** change the assembly definition files

**Comment by lupidan** [comment]
> I am testing these settings because I've had an app rejected again (after Big Sur release and M1 entry), I don't know if it has to do with this plugin so I am checking each plugin in the project and I need to make sure I have the correct settings for your great asset.

Normally you get a rejection reason. What was the reason?

**Comment by sergiosolorzano** [comment]
Thank you for your guidance @lupidan . But sometimes we build for iOS , other for macOS, what settings should I use for AppleAuth-General and MacOS Apple Auth Manager.bundle if I build for macOS?  As you say I'll check include editor only for Apple Auth.Editor.

It's weird , after all day trying and several crashes I got it to compile: I have apple auth.editor with only editor and macOS checked in and it compiles for both dev and release, and works fine on dev, can't tell on release. If you don't mind me saying by way of constructive feedback I think it would really help all users documenting what these options should be set to.

I will do as you suggest, refresh , reimport and rebuild.

The reason apple gave is it froze at the start, and the first thing happening in the game is checking if the user is authorised and authenticated with apple sign in plugin, which led me to believe that maybe it could have something to do with this. A frozen screen didn't happen in the prior version I had approved by Apple before Big Sur and M1.

**Comment by lupidan** [comment]
> If you don't mind me saying by way of constructive feedback I think it would really help all users documenting what these options should be set to.

It's not documented because **YOU DON'T HAVE TO MODIFY THOSE OPTIONS**. They should work as they are whatever platform you build.

* AppleAuth assembly is for Any Platform
* AppleAuth.Editor assembly is ONLY for the Editor
* The MacOAppleAuthManager.bundle is ONLY for Standalone, and it should be automatically set to Any CPU on macOS

Again, you shouldn't need to modify ANYTHING in there. Those settings should not be touched.

> Has anyone had an app approved for macOS by apple with the latest plugin after Big Sur release?

None has reached to me yet regarding this, so I don't know.
The support for the M1 chip is experimental. I don't have an M1 machine to test it out. Theoretically, it should work.

I also don't know the build method you are using. This plugin does not fully support macOS builds through Xcode project generation. But it's in the roadmap.
https://github.com/lupidan/apple-signin-unity/projects/1

**Comment by sergiosolorzano** [comment]
Yeah but if I understand it correctly, through rosetta it'll recompile for M1. I dont know if Apple is testing for M1 too when anyone submits a build. I have asked awaiting an answer.
I am code signing following your tutorial. I didn't change any of those settings when I submitted and had the app rejected. Before Big Sur no problems, now something happens but again, I am not saying it is this plugin, I am diligently trying to cover all settings to make sure it's correct. Your messages are very helpful.

**Comment by sergiosolorzano** [comment]
Hello @lupidan 

Great news, I had the app approved overnight ! 

The settings were those I got working fiddling around, before I got your suggestion to import a fresh copy of the plugin. [Here's a link to the seetings](https://drive.google.com/file/d/1LzKhrXyeispvBq29seX7_cpuwnOJGzDS/view?usp=sharing) I used for the approved app in case they help anyone in the future.

I think the leap from Big Sur beta 11.01 to Big Sur 11.1 released 14th Dec made the difference but most importantly your update on the libraries to use Any Cpu !! Thanks so much @lupidan !

I didn't get any answers from Apple as to the steps to repro frozen grey screens at login, neither did they answer whether they are testing on M1. Very Apple-like ofc. But I really think they test on M1 and so submitting with Any cpu for this plugin is a requirement.

One final question please - @lupidan would you please be so kind to explain what the setting Load on startup does and why you'd suggest having this checked off?

Thanks a bunch for your help !

**Comment by lupidan** [comment]
It shouldn't make a difference for this plugin:
https://forum.unity.com/threads/plugin-inspector-load-on-startup-option.888280/

I will re-iterate though, you don't need to change the default settings.
Your project now won't work properly with iOS builds.

What Unity version is this one?, is the first time I see the GUIDs option

**Comment by sergiosolorzano** [comment]
Thank you for letting me know, fortunately this project is macos only. I'll add a refresh for the next update.
This is Unity 2020.2.0b14
