### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by kympressley** [lupidan/apple-signin-unity#98]
In the firebase documentation, the login and quick login were adapted. However, It doesn't tell you how to call these functions.

How would you call AttemptQuickLogin for firebase if you had an event or button that needed to trigger it?

**Comment by lupidan** [comment]
Please educate yourself about C# Actions, delegates and lambda expresions:
https://docs.microsoft.com/en-gb/dotnet/api/system.action-1?view=net-5.0
https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/operators/lambda-expressions

This is not an issue
